### ISSUE TITLE
Looking for example: how to programmatically change the current time on the VideoPlayer

### ISSUE THREAD

**Issue by slickdev** [shahen94/react-native-video-processing#100]
Hello,

I've tried figuring this out for awhile but haven't had any luck. I want to wire up logic from the tracker on the trimmer component to the play time on the video. My tracker is wired up to the video, so it displays the current time, however I want to be able to move the tracker and skip back and forth through the video accordingly. How can I achieve this?

Thanks in advance.

**Comment by shahen94** [comment]
Here's an quick exmaple(code snippet)

Please take a look at `trimmerPosition` variable
```
<VideoPlayer
            ref={(ref) => this.playerReferences[video.id] = ref}
            source={this.getVideoSource(video)}
            playerWidth={this.styles.playerWidth}
            playerHeight={this.styles.playerHeight}
            play={video.play}
            style={this.styles.previewItem}
            startTime={video.startTime}
            endTime={video.endTime}
            currentTime={video.currentTime} // current-time
            onChange={({ nativeEvent }) => this.setState({ trimmerPosition: nativeEvent.currentTime })}
          />
<Trimmer
              source={trimmedSource}
              width={WINDOW_WIDTH}
              currentTime={this.state.trimmerPosition}
              showTrackerHandle={true}
              height={NAVBAR_HEIGHT}
              trackerColor={PINK}
              themeColor={DARK_GRAY}
            />
```

**Comment by slickdev** [comment]
Thanks, I didn't realize we could have a currentTime on the VideoPlayer component. Actually what I was trying to do is the opposite of this, I wanted the trimmer to control the video. But your code helped me figure it out. Thanks again.

**Comment by slickdev** [comment]
Reopened this because I keep encountering strange issues. If you don't mind, could you let me know how you'd recommend to handle this? What I want to do is have the trimmer and videoplayer on one view. When the video plays, the trimmer tracker should move with it. When the user grabs the trimmer tracker to adjust the playhead, it should change the video accordingly.

This is what my setup looks like:

    <Trimmer
            source={params.photos[params.index].node.image.uri}
            height={80}
            showTrackerHandle={true}
            width={Dimensions.get('window').width}
            onTrackerMove={(e) => this.setState({ trackerPosition: e.currentTime })} // iOS only
            currentTime={this.state.currentTime} // use this prop to set tracker position iOS only
            themeColor={'#f04e37'} // iOS only
            thumbWidth={25} // iOS only
            trackerColor={'#f04e37'} // iOS only
            style={{  }}
            onChange={(e) => this.setState({startTime: e.startTime, endTime: e.endTime})}
        />

        <TouchableOpacity activeOpacity={1} style={{ flex: 1, alignSelf: 'stretch' }} onPress={() => {this.togglePlay()}}>
          <VideoPlayer
              ref={ref => this.videoPlayerRef = ref}
              currentTime={this.state.trackerPosition}
              startTime={this.state.startTime}  // seconds
              endTime={this.state.endTime}   // seconds
              play={this.state.play}     // default false
              volume={this.state.volume}
              replay={true}   // should player play video again if it's ended
              rotate={false}   // use this prop to rotate video if it captured in landscape mode iOS only
              source={params.photos[params.index].node.image.uri}
              playerWidth={Dimensions.get('window').width} // iOS only
              playerHeight={340} // iOS only
              style={{ backgroundColor: '#F05338'}}
              resizeMode={VideoPlayer.Constants.resizeMode.COVER}
              onChange={({ nativeEvent }) => { this.checkForEnd(nativeEvent.currentTime) }} // get Current time on every second
          />


Is my approach to this wrong? How can I improve it? Thanks in advance.

**Comment by slickdev** [comment]
I notice that the currentTime ends up sometimes going past the endTime which is also causing strange issues.

**Comment by shahen94** [comment]
Closing this due to long inactivity, probably this issue has been fixed in the master branch.
Thanks
