### ISSUE TITLE
Horizontal Flip video using ffmpeg?

### ISSUE THREAD

**Issue by rad182** [shahen94/react-native-video-processing#103]
Hi, is there a way to horizontal flip a video? I'm getting an un-mirrored video from the front camera.

**Comment by shahen94** [comment]
FFMPEG have such functionality
https://duxyng.wordpress.com/2013/04/07/rotateflip-video-with-ffmpeg/

But right now in the library we doesn't use this. But you can add  `flip` key for `trim` and for `compress` and open PR. I'll merge it.

Thanks
