### ISSUE TITLE
Android app crashing ProcessingManager.compress

### ISSUE THREAD

**Issue by AlmogRnD** [shahen94/react-native-video-processing#104]
My app keeps crashing when I try to run ProcessingManager.compress

Maybe my source is incorrect here is my code 

```
 ProcessingManager.compress(response.uri, videoOptions) 
                    .then((data) => console.log(data));
```
Also how do you catch errors?

**Comment by AlmogRnD** [comment]
Here is the error from my crash reporting 

```
UnexpectedNativeTypeException: TypeError: expected dynamic type `string', but had type `object'
    at com.facebook.react.bridge.ReadableNativeArray.getString(ReadableNativeArray.java)
    at com.facebook.react.bridge.JavaMethodWrapper$5.extractArgument(JavaMethodWrapper.java:75)
    at com.facebook.react.bridge.JavaMethodWrapper$5.extractArgument(JavaMethodWrapper.java:71)
    at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:350)
    at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:162)
...
(7 additional frame(s) were not displayed)

NativeArgumentsParseException: TypeError: expected dynamic type `string', but had type `object' (constructing arguments for RNTrimmerManager.compress at argument index 0)
    at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:357)
    at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:162)
    at com.facebook.react.bridge.queue.NativeRunnable.run(NativeRunnable.java)
    at android.os.Handler.handleCallback(Handler.java:751)
    at android.os.Handler.dispatchMessage(Handler.java:95)
...
(4 additional frame(s) were not displayed)
```

**Comment by AlmogRnD** [comment]
Here is the error that I'm now getting 

console.js:26 Possible Unhandled Promise Rejection (id: 0):
Error: compress error: failed. ffmpeg version 3.3 Copyright (c) 2000-2017 the FFmpeg developers  built with gcc 4.8 (GCC)  configuration: --target-os=linux --cross-prefix=/Users/kesha/Projects/ffmpeg-android/toolchain-android/bin/arm-linux-androideabi- --arch=arm --cpu=cortex-a8 --enable-runtime-cpudetect --sysroot=/Users/kesha/Projects/ffmpeg-android/toolchain-android/sysroot --enable-pic --enable-libx264 --enable-libass --enable-libfreetype --enable-libfribidi --enable-libmp3lame --enable-fontconfig --enable-pthreads --disable-debug --disable-ffserver --enable-version3 --enable-hardcoded-tables --disable-ffplay --disable-ffprobe --enable-gpl --enable-yasm --disable-doc --disable-shared --enable-static --pkg-config=/Users/kesha/Projects/ffmpeg-android/ffmpeg-pkg-config --prefix=/Users/kesha/Projects/ffmpeg-android/build/armeabi-v7a --extra-cflags='-I/Users/kesha/Projects/ffmpeg-android/toolchain-android/include -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=2 -fno-strict-overflow -fstack-protector-all' --extra-ldflags='-L/Users/kesha/Projects/ffmpeg-android/toolchain-android/lib -Wl,-z,relro -Wl,-z,now -pie' --extra-libs='-lpng -lexpat -lm' --extra-cxxflags=  libavutil      55. 58.100 / 55. 58.100  libavcodec     57. 89.100 / 57. 89.100  libavformat    57. 71.100 / 57. 71.100  libavdevice    57.  6.100 / 57.  6.100  libavfilter     6. 82.100 /  6. 82.100  libswscale      4.  6.100 /  4.  6.100  libswresample   2.  7.100 /  2.  7.100  libpostproc    54.  5.100 / 54.  5.100content://media/external/video/media/8272: Protocol not foundDid you mean file:content://media/external/video/media/8272?
Error: compress error: failed. ffmpeg version 3.3 Copyright (c) 2000-2017 the FFmpeg developers  built with gcc 4.8 (GCC)  configuration: --target-os=linux --cross-prefix=/Users/kesha/Projects/ffmpeg-android/toolchain-android/bin/arm-linux-androideabi- --arch=arm --cpu=cortex-a8 --enable-runtime-cpudetect --sysroot=/Users/kesha/Projects/ffmpeg-android/toolchain-android/sysroot --enable-pic --enable-libx264 --enable-libass --enable-libfreetype --enable-libfribidi --enable-libmp3lame --enable-fontconfig --enable-pthreads --disable-debug --disable-ffserver --enable-version3 --enable-hardcoded-tables --disable-ffplay --disable-ffprobe --enable-gpl --enable-yasm --disable-doc --disable-shared --enable-static --pkg-config=/Users/kesha/Projects/ffmpeg-android/ffmpeg-pkg-config --prefix=/Users/kesha/Projects/ffmpeg-android/build/armeabi-v7a --extra-cflags='-I/Users/kesha/Projects/ffmpeg-android/toolchain-android/include -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=2 -fno-strict-overflow -fstack-protector-all' --extra-ldflags='-L/Users/kesha/Projects/ffmpeg-android/toolchain-android/lib -Wl,-z,relro -Wl,-z,now -pie' --extra-libs='-lpng -lexpat -lm' --extra-cxxflags=  libavutil      55. 58.100 / 55. 58.100  libavcodec     57. 89.100 / 57. 89.100  libavformat    57. 71.100 / 57. 71.100  libavdevice    57.  6.100 / 57.  6.100  libavfilter     6. 82.100 /  6. 82.100  libswscale      4.  6.100 /  4.  6.100  libswresample   2.  7.100 /  2.  7.100  libpostproc    54.  5.100 / 54.  5.100content://media/external/video/media/8272: Protocol not foundDid you mean file:content://media/external/video/media/8272?
    at createErrorFromErrorData (http://localhost:8081/index.android.bundle?platform=android&dev=true&hot=false&minify=false:1745:15)
    at http://localhost:8081/index.android.bundle?platform=android&dev=true&hot=false&minify=false:1702:25
    at MessageQueue.__invokeCallback (http://localhost:8081/index.android.bundle?platform=android&dev=true&hot=false&minify=false:2049:16)
    at http://localhost:8081/index.android.bundle?platform=android&dev=true&hot=false&minify=false:1842:15
    at MessageQueue.__guard (http://localhost:8081/index.android.bundle?platform=android&dev=true&hot=false&minify=false:1980:9)
    at MessageQueue.invokeCallbackAndReturnFlushedQueue (http://localhost:8081/index.android.bundle?platform=android&dev=true&hot=false&minify=false:1841:13)
    at http://localhost:8081/debuggerWorker.js:72:58

**Comment by AlmogRnD** [comment]
I'm closing this have it working using path and not uri

**Comment by shahen94** [comment]
Hi @AlmogRnD !
Your video URI isn't in correct mode - so we should check it

So what we should do:
  1. We should check if file protocol starts with `content` then parse it as URI (`URI.parse(source)`)
  2. pass it to ffmpeg in correct format https://github.com/shahen94/react-native-video-processing/blob/master/android/src/main/java/com/shahenlibrary/Trimmer/Trimmer.java#L421

Unfortunately i have no time to work on this issue, but if you'll fix and open PR  - I'll merge it
