### ISSUE TITLE
How do I catch errors, failures and progress 

### ISSUE THREAD

**Issue by AlmogRnD** [shahen94/react-native-video-processing#107]
I wanted to know if it's possible to catch errors, failures, and progress? Is there a simple code example?

**Comment by shahen94** [comment]
You can catch `progress` event - Please check the `onChange` prop of `VideoPlayer` .

There's no way to catch `Errors` - and we don't have it in roadmap.
But if you could do it - i'll merge that PR immediately

**Comment by AlmogRnD** [comment]
@shahen94 I'm not using the video player but the ProcessingManager is that the same do you have simple code example with this that I can look at ?

**Comment by shahen94** [comment]
Do you want to catch `progress` in processing manager ?

**Comment by AlmogRnD** [comment]
Yes that is correct?

**Comment by shahen94** [comment]
Hm how you want to catch the progress if video doesn't playing ?.

ProcessingManager provides some processing methods like compress/trim/getVideoPreview etc.

And returns promise - so for failures you can add `.catch()` method after `.then()`. and catch failures, but you can't get progress since video doesn't playing

**Comment by AlmogRnD** [comment]
@shahen94 I'm using the ProcessingManager to compress my videos before I upload them as this takes some time it would be nice to have an option to listen to the progress and provider my users with a progress bar.

**Comment by shahen94** [comment]
@AlmogRnD oh gotcha - Swift have similar API, we can catch progress event.
But right now it's not provided to JS, if you familiar with native development and you could open PR with suggested changes i'll take a look
