### ISSUE TITLE
Can't compile on iOS - error 

### ISSUE THREAD

**Issue by AlmogRnD** [shahen94/react-native-video-processing#110]
I can't compile on iOS getting the following error 

Check dependencies

Swift is not supported for static libraries.

**Comment by shahen94** [comment]
Please check this two threads.
https://github.com/shahen94/react-native-video-processing/issues/79
https://github.com/shahen94/react-native-video-processing/issues/48

**Comment by AlmogRnD** [comment]
@shahen94 I'm getting the following error 

error opening input file '/Users/Almog/Full-Time-Employment/Construction-Cloud/RnD/CCMobileApp/node_modules/react-native-video-processing/ios/RNVideoProcessing-Bridging-Header.h' (No such file or directory)

**Comment by AlmogRnD** [comment]
@shahen94 I looked at #79 and #48, I also followed the video guide but that seems outdated maybe just do a well-written doc. 

But for the video file when trying to link the libs I'm missing the following files there not in the folders

 -  ICGThumbView.m
 - RNVideoTimmerBride.m
 
There are more, it's seems the project has changes or been updated

**Comment by shahen94** [comment]
https://github.com/shahen94/react-native-video-processing/blob/master/ios/RNVideoProcessing/RNVideoTrimmer/RNVideoTrimmerBridge.m

https://github.com/shahen94/react-native-video-processing/blob/master/ios/RNVideoProcessing/RNTrimmerView/ICGVideoTrimmer/ICGThumbView.m

Both files are exists in the project. Video demonstrates installation process correctly. Please unlink all files/remove and try again

**Comment by AlmogRnD** [comment]
@shahen94 I followed the video exactly, attached screenshots as you can see everything is correct but I'm still getting  "error opening input file '/Users/Almog/Full-Time-Employment/Construction-Cloud/RnD/CCMobileApp/node_modules/react-native-video-processing/ios/RNVideoProcessing-Bridging-Header.h' (No such file or directory)"

![screen shot 2017-10-09 at 10 24 01 am](https://user-images.githubusercontent.com/169507/31322075-04e54194-acdc-11e7-8437-a86f737eb5c0.png)
![screen shot 2017-10-09 at 10 23 53 am](https://user-images.githubusercontent.com/169507/31322076-04e5a4f4-acdc-11e7-916a-1f36315aa24a.png)
![screen shot 2017-10-09 at 10 21 28 am](https://user-images.githubusercontent.com/169507/31322073-04d3b974-acdc-11e7-91d6-a3fd180d1854.png)
![screen shot 2017-10-09 at 10 21 06 am](https://user-images.githubusercontent.com/169507/31322074-04d40e06-acdc-11e7-8733-7013ed149ba5.png)

**Comment by AlmogRnD** [comment]
If I copy "RNVideoProcessing-Bridging-Header.h" to the requested folder from the error I get 62 errors on build attached screenshot. Is this package fully working on iOS?   

![screen shot 2017-10-09 at 10 29 01 am](https://user-images.githubusercontent.com/169507/31322103-b55367b8-acdc-11e7-8415-8682ace73f77.png)

**Comment by AlmogRnD** [comment]
OK I got past the build errors, the core issue is that you can't run react native link, which is somewhat problematic if you add new packages that require this. Closing this for now
