### ISSUE TITLE
Crazy errors on iOS with compile sources 

### ISSUE THREAD

**Issue by AlmogRnD** [shahen94/react-native-video-processing#113]
If I added the compiled sources, based on the video instructions (attached screenshot) I got 67 errors on build attached screenshot of errors. 

Compiled source 
![screen shot 2017-10-09 at 12 18 57 pm](https://user-images.githubusercontent.com/169507/31322971-3b0fa79a-acec-11e7-9c82-b56a1bd0a54a.png)
 

Errors list 
![screen shot 2017-10-09 at 12 20 14 pm](https://user-images.githubusercontent.com/169507/31322975-451837a2-acec-11e7-9daf-5d901bfbbcc5.png)

If I remove the compiles source, I get no errors and it builds

**Comment by shahen94** [comment]
Please watch this demonstration video https://www.youtube.com/watch?v=HRjgeT6NQJM&feature=youtu.be

You doesn't linked library correctly.

**Comment by AlmogRnD** [comment]
@shahen94 Hi, I watched the video again twice and followed it step by step. I'm getting 67 errors on a build for iOS. Pretty sure something with the package. I'm using new Xcode version and when selecting linked frameworks and libraries it's IOS 11.0 and I noticed in the video it's a different version have you tested on this version with the latest Xcode.

**Comment by AlmogRnD** [comment]
Attached screenshots, as you can exactly like the video 
![screen shot 2017-10-10 at 6 25 49 pm](https://user-images.githubusercontent.com/169507/31374254-f4221d60-ade8-11e7-9af9-d6ba1207301c.png)

![screen shot 2017-10-10 at 6 26 55 pm](https://user-images.githubusercontent.com/169507/31374268-fa5339a8-ade8-11e7-85fc-7d1ad7f7c95c.png)

![screen shot 2017-10-10 at 6 26 47 pm](https://user-images.githubusercontent.com/169507/31374272-fe243e4c-ade8-11e7-8616-23134cce1364.png)

![screen shot 2017-10-10 at 6 27 08 pm](https://user-images.githubusercontent.com/169507/31374277-03f3e610-ade9-11e7-9d05-d98950259fde.png)

**Comment by AlmogRnD** [comment]
The Errors:
![screen shot 2017-10-10 at 6 27 51 pm](https://user-images.githubusercontent.com/169507/31374290-15ae3b76-ade9-11e7-904f-a567e746c99d.png)

![screen shot 2017-10-10 at 6 28 00 pm](https://user-images.githubusercontent.com/169507/31374294-180c135c-ade9-11e7-8ce1-c0983234478d.png)

**Comment by shahen94** [comment]
Which react-native version you're using for ?

**Comment by shahen94** [comment]
you should attach `React` prefix for your all imports

instead of 
```
import "RCTView.h"
```
your should import it like this
```
import "React/RCTView.h"
```

**Comment by AlmogRnD** [comment]
I'm on 
"react-native": "0.48.4",
 "react": "16.0.0-alpha.12",

**Comment by AlmogRnD** [comment]
I tried the following import and still getting the same errors 

```
#import <React/RCTRootView.h>
#import <React/RCTView.h>
#import <React/RCTBridgeModule.h>
#import "React/RNVideoProcessing.h"
```
```

#import <React/RCTRootView.h>
#import <React/RCTView.h>
#import <React/RCTBridgeModule.h>
#import "RNVideoProcessing.h"
```
```

#import <React/RCTRootView.h>
#import <React/RCTView.h>
#import <React/RCTBridgeModule.h>
#import <React/RNVideoProcessing.h>
```

The errors are code errors, are you supporting the latest version

**Comment by shahen94** [comment]
Yes - we're supporting RN 0.48 . Our app is using RN 0.48 and this library together and it's working.

Sorry but i have no idea why you're getting this error, maybe @gevorg94 have some ideas ?

**Comment by AlmogRnD** [comment]
Well if it was one error, I think I could understand a bit more but I'm getting over 60+ errors, across each file. 

For example in `/Users/Almog/Full-Time-Employment/Construction-Cloud/RnD/CCMobileApp/node_modules/react-native-video-processing/ios/RNVideoProcessing/RNTrimmerView/RNTrimmerView.swift`

Only classes that inherit from NSObject can be declared @objc
Use of undeclared type 'RCTView'
Use of undeclared type 'ICGVideoTrimmerView'
Use of undeclared type 'RCTBridge'

**Comment by AlmogRnD** [comment]
@shahen94 Did you use react-native init to create your project?

**Comment by AlmogRnD** [comment]
@shahen94 you can leave this up or close this, I removed your package and now using - https://github.com/phuochau/react-native-compress

It's just simpler and better, this would be my feedback

1. Very easy to install just react link, with your package the iOS installation is very problematic even with the video I don't think this is a long-term solution and I'm not sure it makes sense to use Swift and React doesn't support this yet.

**Comment by shahen94** [comment]
@AlmogRnD You can't link this library just running `react-native link` since Swift is not supported for static libraries.

We wrote in Swift since we know Swift better than Objective-C. This is a open-source project and everyone can contribute - if someone have any ideas how to make the installation process little bit easy - please contact with me. I can see your point, I know it's hard to link iOS project when you're not familiar with iOS native development.

I'll close this since we already had 2-3 issues related to linking process

**Comment by AlmogRnD** [comment]
@shahen94 I don't mind having the process but as you can see from my reports it's not working from me and followed the video exactly as it is.

**Comment by maxhalty** [comment]
+1

**Comment by jolinkomo-code** [comment]
I have the exact same problem!

**Comment by FacuAcosta** [comment]
Okay, I spent 2 hours trying to get this to work, so I'll post what I've done, not sure If I'm missing something because I was really mad. If you followed the video, you should have a `<Project-Name>_Bridging_Header.h` file under `ProjectName/ProjectName` . This file, as stated above, should contain the next data:

```
#ifndef ProjectName_Bridging_Header_h
#define ProjectName_Bridging_Header_h

#import <React/RCTRootView.h>
#import <React/RCTView.h>
#import <React/RCTBridgeModule.h>
#import "RNVideoProcessing.h"

#endif /* ProjectName_Bridging_Header_h */

```

Under Build Settings under your project, you need to set the following flags:
- `Swift Compiler - General / Objective-C Bridging Header` set to `ProjectName/ProjectName_Bridging_Header.h`
- `Swift Compiler - Language / Swift Compiler Version` set to `Swift 3.2`

And that should fix things, If not, just read the errors that xCode gives and try to figure out what fails.

**Comment by prashantShrivastava91** [comment]
Even after following the video, my xcode project wasn't compiling. But `react-native unlink react-native-video-processing` did the trick. Spent days on linking things, but it worked like a charm

**Comment by AMINEDGE** [comment]
I also did the @prashantShrivastava91 and @FacuAcosta Instructions and it worked, another thing that I had an issue with was the Bridging-Header file, I use React Native 0.57 and XCode 10 and my project didn't have the bridging header file, also I couldn't find Swift Compiler option in build settings, I could create the file by creating a new swift file and after that xcode asks you to create bridging-header file, then after it creates the file you can delete the created swift file

**Comment by anmol-appzoy** [comment]
There is no swift 3.2 option available for xCode is there any other solution for that.
