### ISSUE TITLE
undefined is not an object (evaluating _reactNative.UIManager.RNVidroProcessing.Contatns)

### ISSUE THREAD

**Issue by AlmogRnD** [shahen94/react-native-video-processing#114]
Getting the following error on startup up, iOS attached screenshot 

![screen shot 2017-10-09 at 12 24 38 pm](https://user-images.githubusercontent.com/169507/31323024-d6a5efde-acec-11e7-9ee8-46df7296e4c6.png)

**Comment by shahen94** [comment]
https://github.com/shahen94/react-native-video-processing/issues/113#issuecomment-335081401
