### ISSUE TITLE
Bug onChange currentTime

### ISSUE THREAD

**Issue by rayashi** [shahen94/react-native-video-processing#120]
I'm trying update on screen the current time, but it seems there is a bug, sometimes the nativeEvent.currentTime is repeating the last currentTime, or even dont go to the total duration, it end before.

For example, I recorded a video with duration of 6 seconds but its loggin like this
![image](https://user-images.githubusercontent.com/1485807/31628873-b1c5ddec-b290-11e7-988c-223414acc60a.png)

here is my code 

```
        <VideoPlayer
          ref={ref => this.videoPlayerRef = ref}
          replay={true}
          play={this.state.playing}
          source={this.props.src}
          style={styles.player}
          onChange={({ nativeEvent }) => {
              console.log(nativeEvent.currentTime)
              this.setState({
                currentTimeSec:nativeEvent.currentTime})
            }
          }
          resizeMode={VideoPlayer.Constants.resizeMode.CONTAIN}/>  
```

**Comment by shahen94** [comment]
Closing this due to long inactivity

**Comment by pisacode** [comment]
It still exists. It is because when current time is set with state, onChange trigger fires when it receives new state, therefore, it flickers between states. Is there an alternative way to set currectTime without state?
