### ISSUE TITLE
iOS build broken on RN 0.48

### ISSUE THREAD

**Issue by gvillenave** [shahen94/react-native-video-processing#123]
I believe #122 is not backwards compatible with RN 0.48:
```
RNVideoProcessingManager.swift:18:25: Overriding method with selector 'constantsToExport' has incompatible type '() -> [AnyHashable : Any]'
RNVideoProcessingManager.swift:27:25: Method does not override any method from its superclass
```

**Comment by shahen94** [comment]
Please use https://github.com/shahen94/react-native-video-processing/commit/0d720401d969e3534182495306128c15013e35ee
Commit for now. Thanks for letting us to know about this issue.

**Comment by gvillenave** [comment]
Any idea when we could fix this? I'm not really familiar with the iOS changes so I'm afraid I won't be much help for a PR.

**Comment by vvavepacket** [comment]
@gvillenave  do you have any temporary workaround? i also encounter this

**Comment by gvillenave** [comment]
@vvavepacket No unfortunately I'm still stuck on commit https://github.com/shahen94/react-native-video-processing/commit/0d720401d969e3534182495306128c15013e35ee until I can upgrade to RN 0.49+
