### ISSUE TITLE
newSource = undefined when selecting video from sd card in android

### ISSUE THREAD

**Issue by hoorsa** [shahen94/react-native-video-processing#124]
hi (sorry for my English).
for Trim:
When i select video from internal storage everything works but when video selected from external storage undefined returned in newSource!

"/storage/emulated/0/DCIM/vid.mp4" WORKS
but 
"/storage/3766-6230/Pictures/Telegram/VID.mp4" NO!

if i use:
ProcessingManager.trim(source, options) 
          .then((data) => console.log(data));
i get this error:
java.io.ioexception: open failed EACCES (permission denied)

i added:

```
<uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />
<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"/>
```
and permission is granted for storage.

in AndroidManifest.xml

RN 0.49
Android emulator and samsung j5 prime (android 6.0 marshmallow)
OS: windows

**Comment by shahen94** [comment]
Please try to use this version.
https://github.com/shahen94/react-native-video-processing/pull/119

We’ll merge it soon

**Comment by friedolinfoerder** [comment]
I've got the same error and tried with https://github.com/kesha-antonov/react-native-video-processing, but the same error occurs.

RN: 0.47.2
Sony Xperia Z5 Android 7.1.1

**Comment by shahen94** [comment]
Guys can you please send me the stacktrace from android studio?

**Comment by hoorsa** [comment]
thank @shahen94 but this update does not fix the problem!
my solution:
after picking the video first copy the file to **CachesDirectoryPath** using [react-native-fs](https://github.com/itinance/react-native-fs) then pass the video file from **CachesDirectoryPath** to video processing. yes i knew this is a temporary solution but worked for me.

**Comment by nitinkumar24** [comment]
Any other solution to this problem?

**Comment by meiqi1992** [comment]
same issue

**Comment by hoorsa** [comment]
@nitinkumar24 @meiqi1992 
Hi,
Add `file://` to the beginning of selected video path if not exist. 
`videoPath = videoPath.substr(0,7) == 'file://' ? videoPath : 'file://'+videoPath;`
