### ISSUE TITLE
How to build the Android project?

### ISSUE THREAD

**Issue by jayrmotta** [shahen94/react-native-video-processing#125]
How can I build the Android project to make some changes I want?

When I try to open it with Android Studio or any gradle command I get the message:

```
FAILURE: Build failed with an exception.

* Where:
Build file '/Users/jayrmotta/Development/empower/react-native-video-processing/android/build.gradle' line: 1

* What went wrong:
A problem occurred evaluating root project 'android'.
> Plugin with id 'com.android.library' not found.
```

**Comment by shahen94** [comment]
you mean you want to open this library with android studio ?

**Comment by jayrmotta** [comment]
Yes, I did it, but I had to modify the **build.gradle** file adding the following:

```
// ..
    minSdkVersion 19
//..
// in the end of the file
buildscript {
  repositories {
    jcenter()
  }

  dependencies {
    classpath 'com.android.tools.build:gradle:2.3.0'
  }
}
```

Matching the `distributionUrl=https\://services.gradle.org/distributions/gradle-3.5-all.zip` on the **gradle-wrapper.properties**

This way I could build the project.
