### ISSUE TITLE
Can't Build on iOS

### ISSUE THREAD

**Issue by soledaddiez** [shahen94/react-native-video-processing#131]
I'm using the package all good in Android, but when I try to use it in iOS I'm stack in step 6.
My project didn't have a MY_PROJECT-bridging-header.h file.

<img width="267" alt="screen shot 2017-11-03 at 2 31 15 pm" src="https://user-images.githubusercontent.com/1656260/32357816-10b2ef12-c0a5-11e7-8743-b85ff1245c24.png">

I try creating one, and now I'm getting errors: 
```Swift Compiler Error -> 'RNVideoProcessing.h' file not found```

Any suggestions, please?

**Comment by soledaddiez** [comment]
I've done all the configuration again following the instructions on this [video](https://www.youtube.com/watch?v=HRjgeT6NQJM&feature=youtu.be), and it is finally working. Thanks!.

**Comment by aelarassi** [comment]
> I've done all the configuration again following the instructions on this [video](https://www.youtube.com/watch?v=HRjgeT6NQJM&feature=youtu.be), and it is finally working. Thanks!.

Doesn't work for last version React Native 0.60+
