### ISSUE TITLE
Trimmer right and left corner not being initialized on their correct place

### ISSUE THREAD

**Issue by jayrmotta** [shahen94/react-native-video-processing#132]
I'm trying to use this trimmer component but the corners are being rendered randomly along the preview images.

Sometimes the right and left corners start in the middle of the sequence of preview images, and sometimes it renders just a little bit far from the extreme corner.

I've been studying the code and suspect there is something with the `PanResponder` and `Animated.View` listener, but I'm not sure yet.

I'll continue studying and making some tests to understand what is making this rendering random, if you guys also have some idea share here to help a friend.

Thanks in advance :)

**Comment by shahen94** [comment]
I'm not sure why this is happening.
On Android Trimmer view was implemented in pure JS. So examining it should be easy.

**Comment by shahen94** [comment]
Closing this due to long inactivity
