### ISSUE TITLE
RNVideoProcessingManager.swift is causing build to fail, after upgrading to Xcode 9

### ISSUE THREAD

**Issue by iMagdy** [shahen94/react-native-video-processing#133]
I've recently upgraded to Xcode 9, and after that, when building, I get failures in `RNVideoProcessingManager.swift` (see screenshot below).

That's weird as I've been using the library for long time, it was working fine, never faced this issue before. Any idea? @shahen94

![image](https://user-images.githubusercontent.com/611426/32658695-e8f74cfa-c623-11e7-8d34-b46ff038131e.png)

**Comment by iMagdy** [comment]
I think this maybe duplicates https://github.com/shahen94/react-native-video-processing/issues/123

**Comment by shahen94** [comment]
@iMagdy  probably you're right.
What version of RN you're using ?

**Comment by iMagdy** [comment]
@shahen94 `0.47.2`

**Comment by iMagdy** [comment]
I'm trying to upgrade RN and see if this will fix the issue.
Will also try upgrading RNVideoProcessing from `1.12.5` to `1.13.0`.

**Comment by iMagdy** [comment]
@shahen94 upgrade seem to break other packages. Should I downgrade your lib to something lower than `1.12.5`?

**Comment by shahen94** [comment]
Yes please try to downgrade this library. Upgrading react-native probably will be little bit hard rather than downgrading this library

**Comment by iMagdy** [comment]
@shahen94 Do you recommend a particular version?

**Comment by iMagdy** [comment]
Build succeeded with versions:

- `react-native-video-processing`: `1.12.6`
- `react-native`: `0.47.2`
