### ISSUE TITLE
how do we actually save the file to phone storage?

### ISSUE THREAD

**Issue by vvavepacket** [shahen94/react-native-video-processing#137]
I see we have this code

```
 ProcessingManager.compress(response.uri, videoOptions) 
                    .then((data) => console.log(data));
```

but, how do we get the data to be actually written as a video file in the user's phone? I'm not seeing any function of this plugin that does it? Thank you.

**Comment by shahen94** [comment]
Please pass 
```
saveToCameraRoll: true
```
If you want to save the processed video in storage.

**Comment by shahen94** [comment]
Please have a look README.md again

**Comment by vvavepacket** [comment]
i think that is for iOS. how about for android (i think android dont have cameraroll)? thank you

**Comment by jolinkomo-code** [comment]
I agree. android is also needed
