### ISSUE TITLE
Android compression quality

### ISSUE THREAD

**Issue by vvavepacket** [shahen94/react-native-video-processing#138]
What is the best approach to control the video compression quality. I tried the compression, and I find the output to be still of higher quality, I wished to downgrade the quality to achieve a much smaller file size. Can you guys direct me where in java code does the compression quality parameters happen? Might help push a PR for this as well. Thank you.

**Comment by shahen94** [comment]
Hi @vvavepacket !
So we didn't use some options but we're passing it.
https://github.com/shahen94/react-native-video-processing/blob/master/android/src/main/java/com/shahenlibrary/Trimmer/Trimmer.java#L412-L413

We need to use these options and pass it to ffmpeg. That's all. :)
