### ISSUE TITLE
can't find the project_name-bridging-header.h file

### ISSUE THREAD

**Issue by kjetilge** [shahen94/react-native-video-processing#14]
Where is the file project_name-bridging-header.h supposed to be located ?

I tried searching for bridging-header.h on my mac with but found no file with my project name as prefix.

Is it possible to use this module with [React Desktop](http://reactdesktop.js.org/docs/) ?

**Comment by gevorg94** [comment]
@kjetilge you can see there how to create the bridging header for your project.
http://www.learnswiftonline.com/getting-started/adding-swift-bridging-header/

**Comment by Tochukwuibe** [comment]
That link you shared was completely useless @gevorg94

**Comment by gevorg94** [comment]
That was 2 years ago @Tochukwuibe
Create .swift file an xCode will suggest you to create ~bridging-header.h file automatically

**Comment by Tochukwuibe** [comment]
apologies for being so crass, does it matter where I create this swift file, and what do I do with the random swift file once I create the bridging header. (sorry don't know too much about swift development). @gevorg94
