### ISSUE TITLE
Not located file in compress and trim (No such file or directory)

### ISSUE THREAD

**Issue by faelsolucoes** [shahen94/react-native-video-processing#142]
Hello!

I use componente ImagePicker to select image/video/photo and it work, but I received the path of vídeo this component and try to use in "ProcessingManager.trim" or "ProcessingManager.compress" but result in error. I finded strange because I used in "ProcessingManager.getVideoInfo" and it worked.

Error:
Object {
  "e": [Error: compress error: failed. ffmpeg version 3.3.5 Copyright (c) 2000-2017 the FFmpeg developers  built with gcc 4.8 (GCC)  configuration: --target-os=linux --cross-prefix=/Users/kesha/Projects/ffmpeg-android/toolchain-android/bin/arm-linux-androideabi- --arch=arm --cpu=cortex-a8 --enable-runtime-cpudetect --sysroot=/Users/kesha/Projects/ffmpeg-android/toolchain-android/sysroot --enable-libx264 --enable-pthreads --disable-debug --disable-ffserver --enable-version3 --enable-hardcoded-tables --disable-ffplay --disable-ffprobe --enable-yasm --disable-doc --disable-shared --enable-static --enable-nonfree --disable-network --enable-gpl --enable-ffmpeg --enable-small --disable-filters --enable-filter=copy --enable-filter=trim --enable-filter=crop --enable-filter=scale --enable-filter=format --pkg-config=/Users/kesha/Projects/ffmpeg-android/ffmpeg-3.3-pkg-config --prefix=/Users/kesha/Projects/ffmpeg-android/build/armeabi-v7a --extra-cflags='-I/Users/kesha/Projects/ffmpeg-android/toolchain-android/include -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=2 -fno-strict-overflow -fstack-protector-all' --extra-ldflags='-L/Users/kesha/Projects/ffmpeg-android/toolchain-android/lib -Wl,-z,relro -Wl,-z,now -pie' --extra-cxxflags= --extra-libs='-lx264 -lm'  libavutil      55. 58.100 / 55. 58.100  libavcodec     57. 89.100 / 57. 89.100  libavformat    57. 71.100 / 57. 71.100  libavdevice    57.  6.100 / 57.  6.100  libavfilter     6. 82.100 /  6. 82.100  libswscale      4.  6.100 /  4.  6.100  libswresample   2.  7.100 /  2.  7.100  libpostproc    54.  5.100 / 54.  5.100file:///data/user/0/com.younner.winkmeup/cache/ExperienceData/%2540faelsolucoes%252FWinkMeUp/ImagePicker/aa32b2bb-e16a-43b8-bd4e-26492110d6c2.mp4: No such file or directory],
}

Example file path: file:///data/user/0/com.younner.winkmeup/cache/ExperienceData/%2540faelsolucoes%252FWinkMeUp/ImagePicker/aa32b2bb-e16a-43b8-bd4e-26492110d6c2.mp4

I created an APP to Android and iOS:
react-native = 0.50.3
react = 16.0.0
react-native-video-processing = 1.13.0

I use this path in my APP without problems. Why didn't component not find the file ?
This component not working IN RN 0.5x ?

Thanks,
Rafael Dorneles

**Comment by faelsolucoes** [comment]
This component not working IN RN 0.5x ?

**Comment by omegatiger** [comment]
In Android, react-native 0.51 + react-native-image-picker 0.26.7, same error.

When call ProcessingManager.compress, crash in **V/MediaMetadataRetrieverJNI: setDataSource**

```
12-08 10:24:58.350 5650-5650/? V/MediaMetadataRetrieverJNI: setDataSource
12-08 10:24:58.358 5650-5650/? A/libc: Fatal signal 6 (SIGABRT), code -6 in tid 5650 (vw.amarok.forum)
```

Call ProcessingManager.getVideoInfo is same error.


```
const OptionImagePickerVideo = {
    title: 'Vídeo',
    mediaType: 'video',
    storageOptions: {
        skipBackup: true,
        path: 'images',
    }
};

//Select video from Google Photos
ImagePicker.launchImageLibrary(OptionImagePickerVideo, (response) => {   
            //response.uri return -> content://com.google.android.apps.photos.contentprovider/-1/2/content%3A%2F%2Fmedia%2Fexternal%2Ffile%2F442/ORIGINAL/NONE/1988160128 

            ProcessingManager.getVideoInfo(response.uri).then(({duration, size}) =>
                 console.log(duration, size)
             );
       
           //OR
            ProcessingManager.compress(source, {width:360, height:640}).then((data) => {
                console.log(data);
            }).catch(e => {
                console.log(e);
            });
});

```

**Comment by faelsolucoes** [comment]
omegatiger in your case I belive to be you path, verify the format that start uri. In my uri is igual the documentation but only works getVideoInfo, verify my uri. Other functions not works. :(

**Comment by gvillenave** [comment]
I'm seeing the same thing as @omegatiger, but I'm still on RN 0.48. Any ideas?

**Comment by shahen94** [comment]
If your video should be loaded over internet then you should first download that video then call compress method

**Comment by shahen94** [comment]
I'm not sure how to process this souce
`content://com.google.android.apps.photos.contentprovider/-1/2/content%3A%2F%2Fmedia%2Fexternal%2Ffile%2F442/ORIGINAL/NONE/1988160128`

**Comment by omegatiger** [comment]
Hii @shahen94 , 

My knowledge is limited on the subject, but I used the react-native-fetch-blob class, where they made an implementation to get the absolute url from the file.

https://github.com/wkh237/react-native-fetch-blob/blob/6bde5167b435e23e334377aa3bb62e8cf7c7e188/android/src/main/java/com/RNFetchBlob/Utils/PathResolver.java

I do not know if this is really the problem.

----------

Using the "fetch" (react-native) function, I can send the file "content: //com.google.android.apps.photos.contentprovider/-1/2/content%3A%2F%2Fmedia%2Fexternal%2Ffile % 2F442 / ORIGINAL / NONE / 1988160128" to the backend.

So I believe the file exists.

**Comment by faelsolucoes** [comment]
Hi @shahen94 ,

I use packeges ImagePicker and DocumentPicker of EXPO to get files local, but next select the file this module sends the video to directory created by module. I beleve that not have permission to access. But is very strange that function getVideoInfo located file return yours informations, already for functions trim end compress sayed not found this file.
Functions are all of the module ProcessingManager (getVideoInfo , trim , compress).

Example file path local: file:///data/user/0/com.younner.winkmeup/cache/ExperienceData/%2540faelsolucoes%252FWinkMeUp/ImagePicker/aa32b2bb-e16a-43b8-bd4e-26492110d6c2.mp4

**Comment by faelsolucoes** [comment]
Hi @shahen94 ,

I resolved my problem using package "DocumentPicker" of EXPO to select my video and next I used package "react-native-get-real-path" to get path real. With the path real I used in your package and all works it.

Thanks

**Comment by shukerullah** [comment]
I am using `react-native-image-picker` too, and it return path which is not readable for `ProcessingManager.compress`. Any solution @shahen94 @faelsolucoes ?

Here `react-native-image-picker` response
```
{
  path: '/storage/emulated/0/DCIM/Camera/VID_20180201_234922.mp4',
  uri: 'content://media/external/video/media/22414'
}
```

**Comment by faelsolucoes** [comment]
Hello shahen94,Use component react-native-get-real-pathto get real Path.You need to use in Android after receive return ImagePicker.showImagePickerExample: let newUri = await RNGRP.getRealPathFromURI(response.uri);In iOS is not necessary.Good workRafael DornelesEm 1 de fev de 2018 5:17 PM, Pir Shukarullah Shah <notifications@github.com> escreveu:I am using react-native-image-picker too, and it return path which is not readable for ProcessingManager.compress. Any solution @shahen94 @faelsolucoes ?
Here react-native-image-picker response
{
  path: '/storage/emulated/0/DCIM/Camera/VID_20180201_234922.mp4',
  uri: 'content://media/external/video/media/22414'
}

**Comment by meiqi1992** [comment]
@faelsolucoes 
RNGRP.getRealPathFromURI(response.uri).then((newUri) => {
                        console.warn('newUri=' + newUri)
                        // newUri = /storage/emulated/0/DCIM/Camera/VID_20190124_142027.mp4
                        
                        ProcessingManager.trim(newUri, options) 
                           .then((data) => {
                                console.warn('data=' + data)

                            }).catch((e) => {
                                console.warn(e)
                            });
                    })
not working, also get error:  ' trim error: failed. /data/user/0.....'

**Comment by faelsolucoes** [comment]
Hello,

I used in my Project diferente, as:

To get Picture or Video I used component: react-native-image-picker
To transform URL of Video, only used in iOS: RNMov2mp4

Example:

ImagePicker.launchImageLibrary(options, (response) => {
          //console.log('Response V path = ', response.path);
          //console.log('Response V uri  = ', response.uri);
        
          if (response.error) {
            console.log('ImagePicker Error: ', response.error);
          }
          else if (!response.didCancel) {

            this.setState({ loading: true },
              () => {
                this.setState({ loading: true, processingVideo: true },
                  async () => {

			let source;
			if (Platform.OS === 'ios') 
			{
			  const { RNMov2mp4 } = NativeModules;
			  let { path } = await RNMov2mp4.convert(response.uri);

			  source = 'file://' + path;
			}
			else {
			  // android
			  source = 'file://' + response.path;
			}

			let info = await ProcessingManager.getVideoInfo(source);
			//console.log('info 0', info);

			if (info.duration < 2) {

			  this.setState({ loading: false, processingVideo: false });
			  Alert.alert('Warning', 'Your video have small time, the time minimum is 2s.');
			}
			else {

			  let pathTrim = null;
			  let pathCompress = null;
			  if (info.duration > 120) {
				// 2 min para o tempo máximo ao video
				const options = {
				  startTime: 0,
				  endTime: 120,
				  //quality: VideoPlayer.Constants.quality.QUALITY_1280x720, // iOS only
				  //saveToCameraRoll: true, // default is false // iOS only
				  //saveWithCurrentDate: true, // default is false // iOS only
				};

				pathTrim = await ProcessingManager.trim(source, options); // like VideoPlayer trim options
				//console.log('cropped', pathTrim);

				info = await ProcessingManager.getVideoInfo(pathTrim);
			  }
			}
                        let newVideo = (pathTrim == null ? source : pathTrim);
                        let pResult = {
				name: newVideo.substring(newVideo.lastIndexOf('/') + 1),
				uri: newVideo,
				width: info.size.width,
				height: info.size.height,
				type: 'video',
			  };

			  this.setState({ imageVideo: pResult },
				() => {
				  this.setState({ loading: false, processingVideo: false });
				});

                  });
              });
          }
        });

I extracted part of my code, case not understand something me question.

Rafael

**Comment by rahamin1** [comment]
I am trying to handle a local file and fail (I am getting 'setDataSource failed').

Tried various file paths, including putting the mp4 file in the same folder of the component:
`source={./sample.mp4}`

and accessing the file located in /sdcard/Download/small.mp4:
`source={'file:///sdcard/Download/sample.mp4'}`

Any idea?

**Comment by chai86** [comment]
You should try react-native-image-picker. See post #30

**Comment by matamicen** [comment]
Hi @faelsolucoes , Can you help me?
if I want just to compress and Trim video on Android and iOS? Do I have to install ffmpeg library? or just npm react-native-video-processing ? 
Thanks! 
Matt.

**Comment by thatgriffith** [comment]
For those still having problem with files on Android that starts with `content://`. Try installing `react-native-fs` and then apply the following function to get path:
```
import RNFS from 'react-native-fs';
...
const getPath = async (url) => {
    const destPath = `${RNFS.TemporaryDirectoryPath}${Math.floor(
      Math.random() * 999999
    )}`;
    await RNFS.copyFile(url, destPath);
    const res = await RNFS.stat(destPath);
    return res.path;
  };
```
