### ISSUE TITLE
Build failed - pointing to wrong path of RNVideoProcessing-Bridging-Header.h

### ISSUE THREAD

**Issue by somonek** [shahen94/react-native-video-processing#143]
### Current Behavior
I have followed the video for manual setup. When building the project I get 
```
<unknown>:0: error: error opening input file '/Users/myusername/Projects/YA/node_modules/react-native-video-processing/ios/RNVideoProcessing-Bridging-Header.h' (No such file or directory)
``` 

### Expected Behavior
Why is it pointing to the wrong path? RNVideoProcessing-Bridging-Header.h is inside RNVideoProcessing

### Your Environment

|            software            | version
| ------------------------------ | -------
| react-native-video-processing  |  1.13.0
| react-native                   |  tried 0.51.0 and 0.50.0
| node                           | v8.9.0

**Comment by shahen94** [comment]
@somonek path should be

`ios/RNVideoProcessing/RNVideoProcessing-Bridging-Header.h` instead of 
`ios/RNVideoProcessing-Bridging-Header.h`

**Comment by somonek** [comment]
@shahen94 

That's what I can't figure out, I'm not setting that anywhere. Where do I need to update that path? 
Thanks in advance

**Comment by somonek** [comment]
@shahen94 
started fresh with the instructions in #144 and it's not happening anymore.

**Comment by WillyRamirez** [comment]
I followed the steps in #144 from the beginning and i still get this error. I never set any path to 
`ios/RNVideoProcessing-Bridging-Header.h` and i wouldn't know where to change it
