### ISSUE TITLE
Cannot read property 'Constants' of undefined

### ISSUE THREAD

**Issue by somonek** [shahen94/react-native-video-processing#145]
### Current Behavior
I have a CRNA ejected app. I've followed the video for setting up the project, also including the instructions in #144 otherwise there are more issues. 
<img width="307" alt="screen shot 2017-12-08 at 19 48 55" src="https://user-images.githubusercontent.com/6585949/33780391-dc8924dc-dc50-11e7-9816-e33744268b30.png">

and it compiles with these errors
<img width="633" alt="screen shot 2017-12-08 at 19 49 58" src="https://user-images.githubusercontent.com/6585949/33780446-1654218a-dc51-11e7-9ec6-e5697d657d51.png">

then I replace all these imports as following
<img width="318" alt="screen shot 2017-12-08 at 19 52 14" src="https://user-images.githubusercontent.com/6585949/33780550-6c222c9c-dc51-11e7-8e93-9e487162389d.png">
and the build succeeds.

My bridging header files is
```
#import <React/RCTRootView.h>
#import <React/RCTView.h>
#import "React/RCTBridgeModule.h"
#import "RNVideoProcessing.h"
```
and when I `import { ProcessingManager } from 'react-native-video-processing';` I get this error 
<img width="318" alt="screen shot 2017-12-08 at 19 52 14" src="https://user-images.githubusercontent.com/6585949/33780874-a5d9ec3a-dc52-11e7-914a-204ed18d9768.PNG">

### Expected Behavior
no error

### Your Environment

|            software            | version
| ------------------------------ | -------
| react-native-video-processing  |  1.13.0
| react-native                   |  0.50.3
| node                           | v8.9.0
| xcode                           | 9.2
| swift version                           | 3.2

**Comment by amberv0** [comment]
Have you added the GPUImage.framework under Embedded Binaries ? Just to make sure :) Though it's unlikely to solve the issue anyway.

**Comment by dioxide** [comment]
i have same problem

**Comment by WillyRamirez** [comment]
Any update on this?

**Comment by shahen94** [comment]
Dublicate https://github.com/shahen94/react-native-video-processing/issues/93

**Comment by nitishlovesandroid** [comment]
i still face the issue cannot read property of constant undefined how to resolve it please help
