### ISSUE TITLE
[Feature Request] Reversing a video

### ISSUE THREAD

**Issue by wassgha** [shahen94/react-native-video-processing#146]
Is there any easy way to implement reversing a video in both iOS/Android? I am totally willing to code this feature if pointed in the right direction!

**Comment by kesha-antonov** [comment]
Android: https://video.stackexchange.com/questions/17738/how-to-use-ffmpeg-command-for-reverse-video

**Comment by JoshM1994** [comment]
I have a branch implementing this feature currently. Android is working (but needs some cleanup). Working on the iOS implementation tomorrow

**Comment by kesha-antonov** [comment]
Awesome! @JoshM1994

**Comment by JoshM1994** [comment]
And the iOS branch - hardly my neatest work but first time experimenting in swift. Any feedback very welcome: https://github.com/shahen94/react-native-video-processing/pull/157

**Comment by shahen94** [comment]
@JoshM1994 looks pretty good, there are some cases where instead of calling print, we also should notify about failure to JS callback.

Looks really great! Thanks.

**Comment by kesha-antonov** [comment]
Nice! Waiting to test it 😄

**Comment by shahen94** [comment]
Merging  PR.

Guys, well done !
