### ISSUE TITLE
How to cancel compression mid-way through

### ISSUE THREAD

**Issue by gusgoose** [shahen94/react-native-video-processing#147]
Is there any way built-in to allow video compression to be stopped when it's mid-way through? I can't see it in the docs but thought it might be in there somewhere.

**Comment by shahen94** [comment]
There's no way to cancel compression or trim

**Comment by gusgoose** [comment]
Understood. Thanks for the reply.

**Comment by VrajSolanki** [comment]
@shahen94 any plans on working on this??

**Comment by shahen94** [comment]
Hi @VrajSolanki.

I have no time to work on this. But if someone will open the PR - I'll accept it
