### ISSUE TITLE
How to set link url in videoplayer component?

### ISSUE THREAD

**Issue by xMajestic** [shahen94/react-native-video-processing#148]
Hello, now i'm using react-native-video-processing but i cant render video with source link 
-- My issue
![capture](https://user-images.githubusercontent.com/35099285/34560505-8d7d466a-f178-11e7-9679-ecee33bc4692.PNG)
-- My link URL
![capture1](https://user-images.githubusercontent.com/35099285/34560514-94d26526-f178-11e7-9540-a0d28793f996.PNG)
-- VideoPlayer component
![capture2](https://user-images.githubusercontent.com/35099285/34560515-95037418-f178-11e7-8abb-62e97a5497b4.PNG)
Pls help. My English is bad!

**Comment by shahen94** [comment]
Your link should point local video and not remote.

Try to download the video and pass local URI to Video component.
