### ISSUE TITLE
how to crop video square

### ISSUE THREAD

**Issue by julien9999** [shahen94/react-native-video-processing#152]
Hi Shahen, seems like a great module.
I got it to work with the example you gave.
Could you please point out how to compress the video in order to allow a video taken from the camera to be cropped square?
Thanks again

**Comment by shahen94** [comment]
Hi @julien9999 
As I know @kesha-antonov  made PR to which allows cropping the video. Maybe he can help you

**Comment by recepkocur** [comment]
How to crop video square? Sorry, we couldn't find your example.

**Comment by shahen94** [comment]
https://github.com/shahen94/react-native-video-processing/blob/master/lib/ProcessingManager/types.ios.js#L57

**Comment by recepkocur** [comment]
> https://github.com/shahen94/react-native-video-processing/blob/master/lib/ProcessingManager/types.ios.js#L57

Thanks for your kind response. Yes, I've seen it one week ago. I've tried "crop" function. However, it tried to crop one part of it. On the other hand, it did not work. It stretched without cropping. I have not figured out the problem yet. I'm sharing the code. Thank you.

`...
// portrait video output 720 x 1280
const aspectRatio =  640 / 480;
const outputWidth = video.width;
const outputHeight = parseInt(outputWidth * aspectRatio);
// target video size 640 x 480
const options = {
   cropWidth: video.width,
   cropHeight: outputHeight,
   cropOffsetX: 0,
   cropOffsetY: parseInt(Math.abs((video.height - outputHeight) / 2)),
}
ProcessingManager.crop(video.uri, options).then(data => {
   console.log('success', data)
}).catch(error => {
   console.log('error', error)
})
`

**Comment by recepkocur** [comment]
I waiting your reply this problem. Thanks.

**Comment by sschiang** [comment]
recepkocur -- did you figure out how the cropping works? I'm getting the same thing also, it just gives back the original file without cropping.

**Comment by jack53519** [comment]
I had the same problem. Specifying "quality" in crop options fixed it for me

**Comment by nica0012** [comment]
@jackwilliams53519 @sschiang @recepkocur Hi, how are you cropping the video? Is there a cropper similar to the trimmer component that I don't see in the documentation? @shahen94

**Comment by azsidaniel** [comment]
> > https://github.com/shahen94/react-native-video-processing/blob/master/lib/ProcessingManager/types.ios.js#L57
> 
> Thanks for your kind response. Yes, I've seen it one week ago. I've tried "crop" function. However, it tried to crop one part of it for Android. It did not work for iOS. It stretched without cropping. I have not figured out the problem yet. I'm sharing the code. Thank you.
> 
> ```
> // portrait video output 720 x 1280
> const aspectRatio =  640 / 480;
> const outputWidth = video.width;
> const outputHeight = parseInt(outputWidth * aspectRatio);
> const options = {
>    cropWidth: video.width,
>    cropHeight: outputHeight,
>    cropOffsetX: 0,
>    cropOffsetY: parseInt(Math.abs((video.height - outputHeight) / 2)),
> }
> ProcessingManager.crop(video.uri, options).then(data => {
>    console.log('success', data)
>    // use video compress for 640 x 480
>    ...
> }).catch(error => {
>    console.log('error', error)
> })
> ```
> 
> "react-native": "0.57.5",
> "react-native-camera": "^1.4.3",
> "react-native-video-processing": "^1.20.0"

Your code helped me a lot, thank you! 👍🏻 
I was trying to crop a video.
