### ISSUE TITLE
[Android] Invalid int exception thrown in getVideoInfo

### ISSUE THREAD

**Issue by gvillenave** [shahen94/react-native-video-processing#153]
Commit a0ec4fd88ab8086364bab60510b277ee825de03a broke the getVideoInfo behavior on Android, since the frame rate is not always an integer, we should use parseDouble instead of parseInt. I will try to find the time to submit a PR to fix this, but that might take a while so if someone else has time that would be great too :)

**Comment by shahen94** [comment]
Thanks @gvillenave. Good catch !

**Comment by friedolinfoerder** [comment]
I've got the same issue. What's the current state of this? Is there a workaround or alternative version I can use?
