### ISSUE TITLE
Cannot compress video size (expected dynamic type 'double',but had type 'object')

### ISSUE THREAD

**Issue by KamalKanal** [shahen94/react-native-video-processing#164]
### Your Environment

|            software            | version
| ------------------------------ | -------
| react-native-video-processing  |  
| react-native                   |  
| node                           |

**Comment by KamalKanal** [comment]
expected dynamic type 'dobule', but had type 'object'

**Comment by shahen94** [comment]
Please complete the description. Closing this.

Feel free to open a new issue and fill the required information.

Thanks
