### ISSUE TITLE
swift 4.2 xcode bulid fail

### ISSUE THREAD

**Issue by meiqi1992** [shahen94/react-native-video-processing#193]
### Your Environment

|            software            | version
| ------------------------------ | -------
| react-native-video-processing  |  
| react-native                   |  
| node                           |

AVLayerVideoGravityResizeAspect' has been renamed to 'AVLayerVideoGravity.resizeAspect

**Comment by Rennzh** [comment]
@shahen94 I am also faced with the same error that I use swift 4+

**Comment by bharatidudhjiya** [comment]
I have same issue
