### ISSUE TITLE
ProcessingManager.compress error on android

### ISSUE THREAD

**Issue by miladrasooli** [shahen94/react-native-video-processing#194]
### Current Behavior
After calling compress function this error appears in catch statement in console

`Error: compress error: failed. /data/user/0/com.exampleapp/files/ffmpeg[1]: syntax error: '��4��4' unexpected`

### Your Environment
Android Oreo (Emulator)

|            software            | version
| ------------------------------ | -------
| react-native-video-processing  |  1.20.0
| react-native                   |   0.55.0
| node                           | 9.9.0

[https://github.com/WritingMinds/ffmpeg-android-java/issues/179](url)

**Comment by shahen94** [comment]
Hi @miladrasooli .
This is a really weird issue. I'll take a look at this next week.

**Comment by miladrasooli** [comment]
Thanks ,
I tested it on real device and it worked!!!

**Comment by shahen94** [comment]
Awesome!

@miladrasooli Actually `FFMPEG` compress takes to long.

**Comment by yogeshchoudhary147** [comment]
@miladrasooli Is working fine on real device but not on android emulator?

**Comment by miladrasooli** [comment]
works on real device but it is slow

**Comment by yogeshchoudhary147** [comment]
@miladrasooli Thanks for your reply. So you are continuing using this library or have you found any alternative?

**Comment by miladrasooli** [comment]
No alternatives yet :(
