### ISSUE TITLE
permission denied while performing processingManager.trim on a sd card file but works fine for internal storage files

### ISSUE THREAD

**Issue by nitinkumar24** [shahen94/react-native-video-processing#196]
### Your Environment

|            software            | version
| ------------------------------ | -------
| react-native-video-processing  |  
| react-native                   |  
| node                           |

**Comment by shahen94** [comment]
hmm, that's weird. Please attach screenshot of the error message

**Comment by nitinkumar24** [comment]
![whatsapp image 2018-11-10 at 00 09 01](https://user-images.githubusercontent.com/25324584/48281607-10480380-e47d-11e8-8fd4-e75e1e39bc8b.jpeg)

**Comment by shahen94** [comment]
Hi @nitinkumar24 .

Please try to add this lines in your `AndroidManifest.xml` file

```xml
<uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE"/>
<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"/>
```
