### ISSUE TITLE
HELP: Native Module not found

### ISSUE THREAD

**Issue by denny64** [shahen94/react-native-video-processing#20]
I've created the bridging header + imported the correct files/folder to the "top level", still not working

**Comment by gevorg94** [comment]
did you imported it like #import "RNVideoProcessing.h"? make sure you have imported all frameworks that are listed in README file, also add GPUImage.framework to your project's Embedded Binaries section

**Comment by denny64** [comment]
@gevorg94 Yes I've imported everything correctly, but it still cannot find the Native Modules :( - is there any example project I can see? Also, do you have any screenshots of what it should look like?

**Comment by gevorg94** [comment]
@denny64 please check your project's Build Phases section, there will be .swift and .m files of RNVideoProcessing project. It should look like this
![screen shot 2016-12-16 at 11 02 36 am](https://cloud.githubusercontent.com/assets/13519034/21254620/eae40320-c37f-11e6-9ca0-763be50e786d.png)

if these files are not included in Build Phases then you need to add them manually.

![screen shot 2016-12-16 at 11 08 16 am](https://cloud.githubusercontent.com/assets/13519034/21254653/34fcecf6-c380-11e6-801c-8716280f1432.png)

To add manually you need to remove all .swift, .h and .m files from RNVideoProcessing folder(note: remove only reference) then from node_modules/react-native-video-processing/ios/RNVideoProcessing folder add all these files to corresponding folder like in picture above. This should add .m and .swift files to your project's Build Phases

**Comment by shahen94** [comment]
@denny64  React native can't  link automatically, since library written on Swift.
You should add files into your project manually. I hope that @gevorg94's answer helped you.

I'm going to close this issue. Feel free to reopen it if your issue isn't solved yet.
