### ISSUE TITLE
ProcessingManager.crop does not work!

### ISSUE THREAD

**Issue by miladrasooli** [shahen94/react-native-video-processing#205]
Hi .  I want to crop a video square pixels, the code succeeds but the result is just like source and not cropped, Here is my code

``` 
const options = {
            cropWidth: Dimensions.get('window').width,
            cropHeight: Dimensions.get('window').width,
             cropOffsetX: 0,
              cropOffsetY: 0}
                     ProcessingManager.crop(response.uri, options).then(data => {
                              console.log('result',data)
                     })
```

**Comment by shubham6996** [comment]
@miladrasooli were you able to crop your video? If yes, please post your code. :)

**Comment by shubham6996** [comment]
@shahen94 can you please tell how to crop a video? I did it using `ProcessingManager.crop` but the video gets cropped out more than what I want it to. Also, could you please tell how `cropOffsetX` and `cropOffsetX` works? Thanks in advance. :)

**Comment by sschiang** [comment]
@shubham6996 did you figure out how the cropping works? I'm getting the same video back in the callback, without any modifications.

**Comment by miladrasooli** [comment]
@sschiang you MUST provide the quality parameter in options , If no quality value is provided , it will use pass through quality and doesn't do anything!

**Comment by sschiang** [comment]
@miladrasooli wow thanks! It worked--you're my hero. I saw that the quality default to "passthrough" but assumed that meant that it would just detect the dimensions itself.

**Comment by miladrasooli** [comment]
Yes , I thought so too , and it did take me a long to figure it out!
