### ISSUE TITLE
Exception thrown while executing UI block: -[RNVideoPlayer setReplay:]: unrecognized selector sent to instance 0x7fe13920adf0 

### ISSUE THREAD

**Issue by Dmitrylolo** [shahen94/react-native-video-processing#215]
After installation tried to launch application with example video

![](https://puu.sh/CZjXK/ab8129934d.png)

|            software            | version
| ------------------------------ | -------
| react-native-video-processing  |  1.20.0
| react-native                   |  0.57.8

**Comment by Thanhcao86** [comment]
.

**Comment by Dmitrylolo** [comment]
we solve issue by reinstalling several times this library

**Comment by zirkc** [comment]
Getting this same issue

**Comment by CCaiden** [comment]
How did you solve this?

**Comment by meetjpatel** [comment]
I've been facing this issue for a while now. I am using Xcode 10.2.1, swift version is 5. I am using latest updated version of code for RNVideoProcessing folder, its still giving me this error. Any solutions please?

**Comment by AhmadRaza786** [comment]
facing same issue, Anyone has resolution on it ?

**Comment by A-Yatsyk** [comment]
I'm having the same problem.
Have anyone find a solution?

**Comment by stefsugar** [comment]
I reinstall it three times and it didn't work, anyone any other tips?

**Comment by pisacode** [comment]
@shahen94 do you know any idea why would this happen?

**Comment by pisacode** [comment]
After reading this [https://teabreak.e-spres-oh.com/swift-in-react-native-the-ultimate-guide-part-2-ui-components-907767123d9e](https://teabreak.e-spres-oh.com/swift-in-react-native-the-ultimate-guide-part-2-ui-components-907767123d9e) I changed `RNTrimmerView.swift` and `RNVideoPlayer.swift` files on xcode. The errors went away but nothing renders on the `VideoPlayer` component and `Trimmer` component throws an error `Exception thrown while executing UI block: CALayer bounds contains NaN: [0 0; nan 20]` . Now I don't know how to proceed.

**Comment by pmella16** [comment]
@pisacode  you can share the files

**Comment by pisacode** [comment]
@pmella16 sure. I also got it all working.

First edit the top part of `RNVideoPlayer.swift` file with the following code:
`let processingFilters: VideoProcessingGPUFilters = VideoProcessingGPUFilters()
    
    var playerVolume: NSNumber = 0
    var player: AVPlayer! = nil
    var playerLayer: AVPlayerLayer?
    
    var playerCurrentTimeObserver: Any! = nil
    var playerItem: AVPlayerItem! = nil
    var gpuMovie: GPUImageMovie! = nil
    
    var phantomGpuMovie: GPUImageMovie! = nil
    var phantomFilterView: GPUImageView = GPUImageView()
    
    let filterView: GPUImageView = GPUImageView()
    
    var _playerHeight: CGFloat = UIScreen.main.bounds.width * 4 / 3
    var _playerWidth: CGFloat = UIScreen.main.bounds.width
    var _moviePathSource: NSString = ""
    var _playerStartTime: CGFloat = 0
    var _playerEndTime: CGFloat = 0
    var _replay: Bool = false
    var _rotate: Bool = false
    var isInitialized = false
    var _resizeMode = AVLayerVideoGravity.resizeAspect
    @objc var onChange: RCTBubblingEventBlock?
    
    let LOG_KEY: String = "VIDEO_PROCESSING"
  
  @objc func setSource(_ val: NSString) {
    source = val
  }
  @objc func setCurrentTime(_ val: NSNumber) {
    currentTime = val
  }
  @objc func setStartTime(_ val: NSNumber) {
    startTime = val
  }
  @objc func setEndTime(_ val: NSNumber) {
    endTime = val
  }
  @objc func setPlayerWidth(_ val: NSNumber) {
    playerWidth = val
  }
  @objc func setPlayerHeight(_ val: NSNumber) {
    playerHeight = val
  }
  @objc func setPlay(_ val: NSNumber) {
    play = val
  }
  @objc func setReplay(_ val: NSNumber) {
    replay = val
  }
  @objc func setRotate(_ val: NSNumber) {
    rotate = val
  }
  @objc func setVolume(_ val: NSNumber) {
    volume = val
  }
  @objc func setResizeMode(_ val: NSString) {
    resizeMode = val
  }`

then the same thing for the `RNTrimmerView.swift` file with the following: 

`var trimmerView: ICGVideoTrimmerView?
    var asset: AVAsset!
    var rect: CGRect = CGRect.zero
    var mThemeColor = UIColor.clear
    var bridge: RCTBridge!
    @objc var onChange: RCTBubblingEventBlock?
    @objc var onTrackerMove: RCTBubblingEventBlock?
    var _minLength: CGFloat? = nil
    var _maxLength: CGFloat? = nil
    var _thumbWidth: CGFloat? = nil
    var _trackerColor: UIColor = UIColor.clear
    var _trackerHandleColor: UIColor = UIColor.clear
    var _showTrackerHandle = false
  
    @objc func setSource(_ val: NSString) {
      source = val
    }
    @objc func setWidth(_ val: NSNumber) {
      width = val
    }
    @objc func setHeight(_ val: NSNumber) {
      height = val
    }
    @objc func setThemeColor(_ val: NSString) {
      themeColor = val
    }
    @objc func setMinLength(_ val: NSNumber) {
      minLength = val
    }
    @objc func setMaxLength(_ val: NSNumber) {
      maxLength = val
    }
    @objc func setCurrentTime(_ val: NSNumber) {
      currentTime = val
    }
    @objc func setTrackerColor(_ val: NSString) {
      trackerColor = val
    }
    @objc func setThumbWidth(_ val: NSNumber) {
      thumbWidth = val
    }
    @objc func setShowTrackerHandle(_ val: NSNumber) {
      showTrackerHandle = val
    }
    @objc func setTrackerHandleColor(_ val: NSString) {
      trackerHandleColor = val
    }`

And the final tweak is for ios is to check if your video file uri starts with `ph://` and if it does change it to this:

`  const appleId = x.uri.substring(5, 41);
    const ext = 'MOV';
    var videoUri = `assets-library://asset/asset.${ext}?id=${appleId}&ext=${ext}`; `

Now clean and build again. hopefully it will work for you as well.

**Comment by tiwariAtkoolkanya** [comment]
Hi @pisacode , 
where i need to paste this code ?
const appleId = x.uri.substring(5, 41);
const ext = 'MOV';
var videoUri = `assets-library://asset/asset.${ext}?id=${appleId}&ext=${ext}`;

**Comment by ebellumat** [comment]
> @pmella16 sure. I also got it all working.
> 
> First edit the top part of `RNVideoPlayer.swift` file with the following code:
> 
> ```
>    let processingFilters: VideoProcessingGPUFilters = VideoProcessingGPUFilters()
>     
>     var playerVolume: NSNumber = 0
>     var player: AVPlayer! = nil
>     var playerLayer: AVPlayerLayer?
>     
>     var playerCurrentTimeObserver: Any! = nil
>     var playerItem: AVPlayerItem! = nil
>     var gpuMovie: GPUImageMovie! = nil
>     
>     var phantomGpuMovie: GPUImageMovie! = nil
>     var phantomFilterView: GPUImageView = GPUImageView()
>     
>     let filterView: GPUImageView = GPUImageView()
>     
>     var _playerHeight: CGFloat = UIScreen.main.bounds.width * 4 / 3
>     var _playerWidth: CGFloat = UIScreen.main.bounds.width
>     var _moviePathSource: NSString = ""
>     var _playerStartTime: CGFloat = 0
>     var _playerEndTime: CGFloat = 0
>     var _replay: Bool = false
>     var _rotate: Bool = false
>     var isInitialized = false
>     var _resizeMode = AVLayerVideoGravity.resizeAspect
>     @objc var onChange: RCTBubblingEventBlock?
> 
>     let LOG_KEY: String = "VIDEO_PROCESSING"
>   
>    @objc func setSource(_ val: NSString) {
>     source = val
>   }
>   @objc func setCurrentTime(_ val: NSNumber) {
>     currentTime = val
>   }
>   @objc func setStartTime(_ val: NSNumber) {
>     startTime = val
>   }
>   @objc func setEndTime(_ val: NSNumber) {
>     endTime = val
>   }
>   @objc func setPlayerWidth(_ val: NSNumber) {
>     playerWidth = val
>   }
>   @objc func setPlayerHeight(_ val: NSNumber) {
>     playerHeight = val
>   }
>   @objc func setPlay(_ val: NSNumber) {
>     play = val
>   }
>   @objc func setReplay(_ val: NSNumber) {
>     replay = val
>   }
>   @objc func setRotate(_ val: NSNumber) {
>     rotate = val
>   }
>   @objc func setVolume(_ val: NSNumber) {
>     volume = val
>   }
>   @objc func setResizeMode(_ val: NSString) {
>     resizeMode = val
>   }
> ```
> 
> **then the same thing for the `RNTrimmerView.swift` file with the following:**
> 
> ```
>    var trimmerView: ICGVideoTrimmerView?
>     var asset: AVAsset!
>     var rect: CGRect = CGRect.zero
>     var mThemeColor = UIColor.clear
>     var bridge: RCTBridge!
>     @objc var onChange: RCTBubblingEventBlock?
>     @objc var onTrackerMove: RCTBubblingEventBlock?
>     var _minLength: CGFloat? = nil
>     var _maxLength: CGFloat? = nil
>     var _thumbWidth: CGFloat? = nil
>     var _trackerColor: UIColor = UIColor.clear
>     var _trackerHandleColor: UIColor = UIColor.clear
>     var _showTrackerHandle = false
>   
>     @objc func setSource(_ val: NSString) {
>       source = val
>     }
>     @objc func setWidth(_ val: NSNumber) {
>       width = val
>     }
>     @objc func setHeight(_ val: NSNumber) {
>       height = val
>     }
>     @objc func setThemeColor(_ val: NSString) {
>       themeColor = val
>     }
>     @objc func setMinLength(_ val: NSNumber) {
>       minLength = val
>     }
>     @objc func setMaxLength(_ val: NSNumber) {
>       maxLength = val
>     }
>     @objc func setCurrentTime(_ val: NSNumber) {
>       currentTime = val
>     }
>     @objc func setTrackerColor(_ val: NSString) {
>       trackerColor = val
>     }
>     @objc func setThumbWidth(_ val: NSNumber) {
>       thumbWidth = val
>     }
>     @objc func setShowTrackerHandle(_ val: NSNumber) {
>       showTrackerHandle = val
>     }
>     @objc func setTrackerHandleColor(_ val: NSString) {
>       trackerHandleColor = val
>     }
> ```
> 
> **And the final tweak is for ios is to check if your video file uri starts with `ph://` and if it does change it to this:**
> 
> ```
> const appleId = x.uri.substring(5, 41);
> const ext = 'MOV';
> var videoUri = `assets-library://asset/asset.${ext}?id=${appleId}&ext=${ext}`;
> ```
> 
> **Now clean and build again. hopefully it will work for you as well.**

WORKS AS WELL! THANKS. PLEASE MAKE A PULL REQUEST FOR THIS PROJECT

**Comment by ebellumat** [comment]
@pisacode I created a PR before you because a lot of people had this same problem using React Hooks. Thanks for your solution.

**Comment by chai86** [comment]
@pisacode @pmella16 @ebellumat @shahen94 

I'm also getting the error: `Exception thrown while executing UI block: CALayer bounds contains NaN: [0 0; nan 50]`

It looks like its happening when i'm trying to call getVideoInfo for a video that's a **square**. (NaN something to do with divide by zero or a variable not having a default?).

I'm using the latest module and my `RNVideoPlayer.swift` and `RNTrimmerView.swift` are as you've mentioned above already and the URL for the file is already: 
`URL = assets-library://asset/asset.MP4?id=3A59DD37-58A6-4988-928F-9AD3B65E65A2&ext=MP4`


```
ProcessingManager.getVideoInfo(URL)
         .then(({ size, duration }) => { 
                                this.setState({
                                                videoWidth: size.width,
                                                videoHeight: size.height,
                                                durationEnd: duration
                                              }); 
                             });   

```
I think this is an outlier case that's perhaps not been addressed and i have no idea how to solve it. Please help!

**Comment by chai86** [comment]
@pisacode @pmella16 @ebellumat @shahen94 

Can you please help on #292 ?
