### ISSUE TITLE
Is there anyway to set the framerate for video compression output?

### ISSUE THREAD

**Issue by lucasfjportela** [shahen94/react-native-video-processing#219]
I'm having some problems with large videos compression and I'd like to know all the valid options for ProcessingManager.compress and if it has a frameRate option to set

**Comment by shahen94** [comment]
![image](https://user-images.githubusercontent.com/13334788/56414046-7ccff580-629a-11e9-8dd3-3fdda2d146f8.png)


We have compression multipliers and bitrates - You can play with these to get the performance that you need.
