### ISSUE TITLE
app crash while change video thumbnail.

### ISSUE THREAD

**Issue by RONAKDHOLARIYA** [shahen94/react-native-video-processing#220]
### Your Environment

|            software            | version
| ------------------------------ | -------
| react-native-video-processing  |  
| react-native                   |  
| node                           |

**Comment by RONAKDHOLARIYA** [comment]
when calling getPreviewForSecond() method it seem to take time to render and the app will crash.

**Comment by chai86** [comment]
@RONAKDHOLARIYA did you get this function to work?

**Comment by ravaliKs** [comment]
IS this issue resolved for you. If yes, can you tell me the solution?
