### ISSUE TITLE
can we compress the video in react native(android only) with using this library ? Is it possible ? 

### ISSUE THREAD

**Issue by harikrishna1213** [shahen94/react-native-video-processing#221]
### Current Behavior
It compressing the video in IOS but is it possible in android ?

### Expected Behavior

We should be able to compress the video in android also. 

### Your Environment

|            software            | version
| ------------------------------ | -------
| react-native-video-processing  |  
| react-native                   |  
| node                           |

**Comment by shahen94** [comment]
Yes - It's possible

**Comment by cpadua88** [comment]
@shahen94 what would be the best way to handle the compression for android. The issue we have right now, sometimes we can compress, and sometimes it won't, regardless of the size.

Thank you!
