### ISSUE TITLE
 Task :app:transformDexArchiveWithExternalLibsDexMergerForDebug FAILED D8: Program type already present: com.coremedia.iso.BoxParser

### ISSUE THREAD

**Issue by harikrishna1213** [shahen94/react-native-video-processing#222]
Here I am getting this issue while integrating react-native-video-processing library to my react-native (android) project.

### Current Behavior
- I have done all steps what those given in readme file but getting above error while running the project. If I remove this library from the build.gradle everything is fine. Please, can anyone tell me the solution for this error?

### Expected Behavior
The app should run without errors.

### Your Environment
Below is my app/build.gradle file

dependencies {

    implementation project(':react-native-video-processing')
    implementation project(':react-native-orientation')
    implementation project(':react-native-linear-gradient')
    implementation project(':react-native-keep-awake')
    implementation project(':react-native-video')
    implementation 'com.iceteck.silicompressorr:silicompressor:2.2.1'
    implementation project(':react-native-maps')
    implementation project(':react-native-location-switch')
    implementation project(':react-native-image-crop-picker')
    implementation fileTree(dir: "libs", include: ["*.jar"])
    implementation "com.android.support:appcompat-v7:${rootProject.ext.supportLibVersion}"
    implementation "com.facebook.react:react-native:+"  // From node_modules
    implementation(project(':react-native-maps')) {
        exclude group: 'com.google.android.gms', module: 'play-services-base'
        exclude group: 'com.google.android.gms', module: 'play-services-maps'
    }

   implementation 'com.google.android.gms:play-services-base:16.+'
    implementation 'com.google.android.gms:play-services-maps:16.+'
}

|            software            | version
| ------------------------------ | -------
| react-native-video-processing  |  
| react-native                   |  
| node                           |

**Comment by waqaramjad** [comment]
same issue
