### ISSUE TITLE
suggestions (PRs will follow if accepted)

### ISSUE THREAD

**Issue by goldylucks** [shahen94/react-native-video-processing#23]
1. remove constructor calls completely
2. use default for exporting components
3. consistency
4. [react/sort-comp](https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/sort-comp.md)
5. advanced reconstructing
6. perf:  VideoPlayer

### NOTE:  
disregard indentation in my examples, PRs will b sent in current linting rules of course

lemme know what u think of these suggestions! :)

## remove constructor calls completely
so this:
```js
export class Trimmer extends Component {
    // ...
  constructor(...args) {
    super(...args);
    this.state = {};
    this._onChange = this._onChange.bind(this);
  }

  _onChange(event) {
    if (!this.props.onChange) {
      return;
    }
    this.props.onChange(event.nativeEvent);
  }
```
becomes:
```js
export class Trimmer extends Component {
//...
  state = {}

  _onChange = (event) => {
      if (!this.props.onChange) {
          return;
      }
      this.props.onChange(event.nativeEvent);
  }
```

## use default for exporting components
this:
```js
// Trimmer/index.js
export { Trimmer } from './Trimmer'

// lib/index.js
export { Trimmer } from './Trimmer';
```
becomes
```js
// Trimmer/index.js
import Trimmer from './Trimmer'
export default Trimmer

// lib/index.js
export Trimmer from './Trimmer';
```

## consistency
whether or not point 3 gets implemented:
this:
```js
export {
  VideoPlayer
} from './VideoPlayer';
export { Trimmer } from './Trimmer';
```
becomes
```js
export { VideoPlayer } from './VideoPlayer';
export { Trimmer } from './Trimmer';
```

## add react/sort-comp
looks like this repo has static methods first, and render is last, in the case your configuration would b something like:
```js
    "react/sort-comp": [2,
      {
        "order": [
          "static-methods",
          "lifecycle", // not sure u need this?
          "everything-else",
          "render",
        ]
      }
    ],
``` 

## advanced reconstructing
this:
```js
// lib/VideoPlayer/VideoPlayer.js
  render() {
    const {
      // ...
      source,
    } = this.props;

    const actualSource = getActualSource(source);
    return (
      <RNVideoPlayer
        source={actualSource}
        // ...
      />
    );
  }
```
becomes
```js
  render() {
    const {
      // ...
      source: getActualSource(source),
    } = this.props;

    return (
      <RNVideoPlayer
        source={source}
        // ...
      />
    );
  }
```

## perf:  VideoPlayer
running `getActualSource(source)` will probably lead to unnecessary processing done by:  
 `import resolveAsset from 'react-native/Libraries/Image/resolveAssetSource';` 

I don't know how expensive this is, tho it might b better to either use [shouldComponentUpdate](https://facebook.github.io/react/docs/react-component.html#shouldcomponentupdate) or something like:

```js
state = {
  source: getActualSource(this.props.source)
}
componentWillReceiveProps(nextProps) {
  if (nextProps.source === this.props.source) {
    return
  }
  this.setState({ source: getActualSource(source) })

  // ...

render() {
      <RNVideoPlayer
        source={this.state.source}
        // ...
      />
}
}
```

**Comment by shahen94** [comment]
@goldylucks good idea, really i like your suggestions.  PR's are welcome, just please commit your changes using `npm run commit`
https://github.com/shahen94/react-native-video-processing#contributing

**Comment by goldylucks** [comment]
sure man, got that the first time ;)

so do u agree with all 5 points?
I'm happy to help, making sure I'm not preparing PRs for nothing

**Comment by shahen94** [comment]
@goldylucks yep, let's do that
