### ISSUE TITLE
error: SWIFT_VERSION '3.0' is unsupported, supported versions are: 4.0, 4.2, 5.0. (in target 'RNVideoProcessing')

### ISSUE THREAD

**Issue by 0xcodezero** [shahen94/react-native-video-processing#236]
I have started developing my current app on RN0.53.3, and It builds successfully on both android and iOS, however currently after upgrading the Xcode version to be able to upload a new build on the store, it rejects to generate the build nor run on the new Xcode, 
On the other hand, Apple rejects any build uploaded to the store/TestFlight from an older version of Xcode as it is no longer supports swift 3 binaries.

I have tried also upgrading **react-native-video-processing** library or **RN to 0.59.10**, but it does not help.

### Current Behavior

Running `react-native run-ios`

Gives a compilation error
`error: SWIFT_VERSION '3.0' is unsupported, supported versions are: 4.0, 4.2, 5.0. (in target 'RNVideoProcessing')`  

## This scenario reproduces the issue:

```
react-native init testingVideoApp
$ cd /THE PROJECT PATH/
$ react-native run-ios  // --> the empty application runs normally
$ npm install react-native-video-processing --save
$ react-native link react-native-video-processing
 /**  It prints
     info Linking "react-native-video-processing" iOS dependency
     info iOS module "react-native-video-processing" has been successfully linked
     info Linking "react-native-video-processing" Android dependency
     info Android module "react-native-video-processing" has been successfully linked
**/

$ react-native run-ios  // --> This time produces the compilation error as above ..
```

## Error 

`error: SWIFT_VERSION '3.0' is unsupported, supported versions are: 4.0, 4.2, 5.0. (in target 'RNVideoProcessing')`  

### Expected Behavior

I expected a way to be able to use the library on the new Xcode standards, as I have tried to update **react-native-video-processing** but I got the same version 1.20.0, 

so What will be the next step, or the best way to get such error resolved?

### Your Environment

|            software            | version
| ------------------------------ | -------
| react-native-video-processing  |  1.20.0
| react-native-video      |  2.3.1
| Xcode version           | 10.2.1
| MacOS              | 10.14.4
| react                     | 16.8.3 
| react-native                   |   0.59.10
| node                           |  10.13.0

**Comment by ramon90** [comment]
I think it won't be resolved as this library has not been updated since 2017

**Comment by 0xcodezero** [comment]
@ramon90 I have checked his commits over the master branch, There is a merge of a pull request to have a migration to swift 4.2, https://github.com/shahen94/react-native-video-processing/pull/216

And @shahen94 has already merged into master, but if you follow his messages it is not fully tested.
So I will try it and respond with the trial feedback.

Thanks, @shahen94, and For sure, @slavasemeniuk

**Comment by ramon90** [comment]
@0xcodezero so, did it work?

**Comment by slavasemeniuk** [comment]
@ramon90 I noticed that #216 hasn't been released yet.

What version of the module are you using? 
I'm not JS dev but you might need to specify the branch at `Package.json` instead of having the version there.

**Comment by ramon90** [comment]
@slavasemeniuk so in Package.json I should have: 
"react-native-video-processing": "https://github.com/shahen94/react-native-video-processing.git",
instead of   "react-native-video-processing": "^1.20.0", 
?

**Comment by 0xcodezero** [comment]
Hi @ramon90,
Sorry for being away for a while, 

For the **package.json** use the following reference to git branch:
`"react-native-video-processing": "git+https://git@github.com/shahen94/react-native-video-processing.git"`

Make sure to clean the **package-lock.json** file, or use the following [Gist](https://gist.github.com/jarretmoses/c2e4786fd342b3444f3bc6beff32098d) for reference

For the sample project that I have created, I have followed the manual integration/linking for react-native-video-processing
and I did **NOT** use `react-native link react-native-video-processing` command.

- Just note that according to the wiki, I have to add a swift file into the project to have a proper bridge-header.h file linked and to import the `RNVideoProcessing.h`
- In addition, also note that according to the images used in the wiki, the `RNVideoProcessing` is added by reference (Blue Folder), but I found that I have to include it as a grouped folder.

Hope it helps @ramon90 ..
And Thanks @slavasemeniuk

**Comment by ramon90** [comment]
@0xcodezero Thanks for your time, can just explain that "bridge-header.h file" step, so I should create a swift file or a .h file? And is that file at the top-level?

**Comment by ramon90** [comment]
@0xcodezero so I followed this video https://www.youtube.com/watch?v=HRjgeT6NQJM&feature=youtu.be and now the project build and runs, but it throws this error: "Cannot read property 'Constants' of undefined". Any idea why is this?

**Comment by ramon90** [comment]
@slavasemeniuk any clue?

**Comment by ramon90** [comment]
I finally got it working. Thanks @0xcodezero. Thanks @slavasemeniuk.

**Comment by 0xcodezero** [comment]
@ramon90 It would be great for the community if you stated the steps you have followed to get it running, as It will be a reference for anyone that could follow the thread.

Also, Can you confirm that your build is working normally on an actual device, or simulator only?

**Comment by 0xcodezero** [comment]
I also suggest that @shahen94 updating npm version from the master, as the 1.20.0 is totally deprecated on the new xcode, which is the allowed version to upload **ipa** to App store.

I could also help with creating an update to the installation wiki to mention such state and the installation steps for iOS which not mentioning importing GPUImage.framework on the Embedded binaries.

**Comment by ramon90** [comment]
@0xcodezero setting it up was not straight forward, because there were errors that I had to fix manually, but, what I did is that I followed all the steps in that video:  https://www.youtube.com/watch?v=HRjgeT6NQJM&feature=youtu.be, also I added Objective-C Bridging Header file name in Build Settings, then when I built and run I was getting compilation errors, which I think is swift version 3 code that needs to be updated, but what I did is that I commented out that code (it was all related to video player) because I needed only one function from that library (compress).

**Comment by 0xcodezero** [comment]
I have closed this issue as It could be resolved using the master branch version of the library, however, this issue still related to 1.20.0 version, And I hope that if the library owner will push a new version to npm.
