### ISSUE TITLE
[IOS] IOS Build error error: SWIFT_VERSION '3.0' is unsupported, supported versions are: 4.0, 4.2, 5.0. (in target 'RNVideoProcessing')

### ISSUE THREAD

**Issue by ebellumat** [shahen94/react-native-video-processing#248]
On try to run on iOS, the build returns this error.

error: SWIFT_VERSION '3.0' is unsupported, supported versions are: 4.0, 4.2, 5.0. (in target 'RNVideoProcessing')

**Comment by CarlosManotas** [comment]
@ebellumat change in your `package.json` `"react-native-video-processing": "1.20.0"` for 
```
"react-native-video-processing": "git+https://git@github.com/shahen94/react-native-video-processing.git"
```

**Comment by ebellumat** [comment]
Works =)
