### ISSUE TITLE
Failed to import GPUImage.h

### ISSUE THREAD

**Issue by barbaragomes** [shahen94/react-native-video-processing#25]
Hey There,

I have followed all the steps described on README.md but I can not figure out why this error is happening

```
/Users/barbaragomes/Projects/intellectmobile/ios/intellectApp-Bridging-Header.h:9:9: note: in file included from /Users/barbaragomes/Projects/intellectmobile/ios/intellectApp-Bridging-Header.h:9:
#import "RNVideoProcessing.h"
        ^
/Users/barbaragomes/Projects/intellectmobile/node_modules/react-native-video-processing/ios/RNVideoProcessing/RNVideoProcessing.h:11:9: error: 'GPUImage.h' file not found
#import "GPUImage.h"
        ^
<unknown>:0: error: failed to import bridging header '/Users/barbaragomes/Projects/intellectmobile/ios/intellectApp-Bridging-Header.h'
```

Any Suggestions?

Also, is it compatible with Swift 3? Or do I have to make the changes to RNProcessingVideo files manually in order to be compatible with Swift3?

**Comment by gevorg94** [comment]
yes it's compatible with Swift 3.
there are some answers with troubleshooting here https://github.com/shahen94/react-native-video-processing/issues/20 .
if it doesn't help you please let me know. I will try to find a solution

**Comment by barbaragomes** [comment]
I saw the issues #20 before posting the question here. At first, it could not find RNVideoProcessing.h . After I added all the files manually it was able to find the RNVideoProcessing.h but it can not find the GPUImage.h.

BTW I'm using react 0.35.0 and iOS 10

![screen shot 2017-02-07 at 4 13 31 pm](https://cloud.githubusercontent.com/assets/13023284/22717526/64bda6a2-ed50-11e6-8cee-e58f660c0a1a.png)

I see all the files inside the folder RNVideoProcessing under the Compile Sources in Build Phases.

![screen shot 2017-02-07 at 4 15 05 pm](https://cloud.githubusercontent.com/assets/13023284/22717559/9af6684e-ed50-11e6-8459-5dda981cea59.png)

Is there anything missing?

**Comment by barbaragomes** [comment]
So, I manage to work around it.

I removed the ```#import 'GPUImage.h'``` and added manually to all the Swift files that uses it ```import GPUImage```

I also had to handle some React issues, like replacing RTCView by UIView in the Swift files.

I'm able to at least get the modules to work, but I still see an exception:

``` 
UIView base class does not support pointerEvent value: box-none
```

Any thoughts?

Thank you

**Comment by barbaragomes** [comment]
I was able to figure stuff out.

I forgot to add ```#import "RCTView.h"``` to my project react bridge.
Once I imported it, I was able to switch back to RTCView instead of UIView and the exception is gone.

I still had to import manually the GPUImage in each file that uses it and remove it from ```RNVideoProcessing.h```. Not sure why tough.

**Comment by flybayer** [comment]
I'm really looking forward to trying this project, but I've spent a couple hours trying to get it working to no avail. 😢 

1. First, I followed the readme instructions.

2. Then, I had to follow the instructions in #20 to get this library to start compiling.

3. Then I had to go through and add `React/` in front of the RCT header file include statements because it seems this hasn't been updated for react-native 0.40+ (see the breaking change release note [here](https://github.com/facebook/react-native/releases/tag/v0.40.0))

4. Then I had to import `React/RCTView.h` in my bridging header file.

5. Now I'm stuck compiling because it can't find `GPUImage.h` included from `RNVideoProcessing.h`. 
@barbaragomes how exactly did you get this to work?

My `project-Bridging-Header.h` currently contains this:
```objc
#import "React/RCTBridgeModule.h"
#import "React/RCTView.h"
#import "RNVideoProcessing.h"
```

**Comment by gevorg94** [comment]
Folks i've added an example to README how to setup library
Check out [this video](https://youtu.be/HRjgeT6NQJM) video, and let me know if your issue isn't solved yet.
Also i want you to know that currently we're not supporting RN 0.4x. We'll push the updates tomorrow to support rn 0.4x

**Comment by shahen94** [comment]
I'm going to close this issue, be free to reopen ths

**Comment by barbaragomes** [comment]
Thank you for the video.

I did the exact same thing that @gevorg94 demonstrated on the video but I was still getting the error that @flybayer mentioned on **item 5**.

@flybayer I remove `#import GPUImage.h` from the `RNVideoProcessing.h` and added the `import GPUImage` manually in each `.swift` file that required it. So far I have had no issues.

Hope that helps

**Comment by shahen94** [comment]
@barbaragomes Thank you for keeping us informed . This PR will fix this issue https://github.com/shahen94/react-native-video-processing/pull/27

**Comment by arunbriskstar** [comment]
> I'm going to close this issue, feel free to reopen this if your issue isn't solved

Still, I am facing the same issue tried to replicate the steps provided in vide by @flybayer 

Please guide
