### ISSUE TITLE
Crash in iPhone 6 due to memory leak

### ISSUE THREAD

**Issue by Rejsal** [shahen94/react-native-video-processing#262]
### Current Behavior
It works okay in iphone x, But crashing in iphone 6. It works Okay when load only trimmer or Video player. Found crash when added both.

### Your Environment

|            software            | version
| ------------------------------ | -------
| react-native-video-processing  |  
| react-native                   |  
| node                           |

**Comment by shahen94** [comment]
Please, copy/paste error, call stack and fill the form before submitting an issue.
thanks

**Comment by Rejsal** [comment]
App crashes when loading the trimmer view. This is printed in IOS during crash.
"CHANGED: Removing Observer, that can be a cause of memory leak".

Note: I can load only trimmer without video player.
