### ISSUE TITLE
Suggestion for people not able to run this library

### ISSUE THREAD

**Issue by ramon90** [shahen94/react-native-video-processing#263]
Since this library is no longer maintained, an alternative  is to run ffmpeg (a library which react-native-video-processing uses for video processing) on the backend instead of the frontend.

**Comment by shahen94** [comment]
This project is maintained by the community - FFMPEG you can run on the backend, but it will not be a solution for various tasks.

FFMPEG is very heavy and running it on the backend could produce performance issues if you'll not manage memory very carefully
