### ISSUE TITLE
Library not loaded - no suitable image found with XCode 11.3

### ISSUE THREAD

**Issue by benscho** [shahen94/react-native-video-processing#268]
I searched the issues before posting this. This issue looks like it could be related to: https://github.com/shahen94/react-native-video-processing/issues/68, but I've tried the listed steps there and the error persists.

I followed the tutorial closely (from what I can tell). This works fine on Android, and I don't see anyone else mentioning this, so I'm thinking the error is probably on my end but I've spent a lot of time and I don't see it yet.

### Current Behavior
I'm able to build and run on the iOS simulator just fine. But when I try to install on my personal device, I get a fatal sigabrt:

> dyld: Library not loaded: @rpath/GPUImage.framework/GPUImage
> 
>   Referenced from: /private/var/containers/Bundle/Application/ECEF7217-E5D3-4ED0-819E-18F6A4FD1810/MyApp.app/MyApp
> 
>   Reason: no suitable image found.  Did find:
> 
> 	/private/var/containers/Bundle/Application/ECEF7217-E5D3-4ED0-819E-18F6A4FD1810/MyApp.app/Frameworks/GPUImage.framework/GPUImage: code signature invalid for '/private/var/containers/Bundle/Application/ECEF7217-E5D3-4ED0-819E-18F6A4FD1810/MyApp.app/Frameworks/GPUImage.framework/GPUImage'

I'm pretty new to iOS development, but that looks like a signing issue. I have a currently valid (trial) iOS signing license, so I'm not sure why I wouldn't be able to sign that framework properly. I have it set to sign and embed in xcode.

### Expected Behavior
I can build and run it on an actual iOS device, and hopefully submit it to the App Store at some point :)

### Your Environment
|            software            | version
| ------------------------------ | -------
| react-native-video-processing  |  shahen94/react-native-video-processing
| react-native                   |  0.60.0
| node                           | 10.16.3
| XCode                         | 11.3

**Comment by BunHouth** [comment]
@benscho  you can try my fork repo https://github.com/Bunhouth/react-native-video-processing
I'm not sure, if it work for you or not but it work fine on my project with latest RN version.

**Comment by mladibejn** [comment]
Hi @BunHouth , I wrote you an email about your fork. I tried to use it but again I am getting certain errors. Maybe you could help me out to resolve them? Thanks in advance!

**Comment by benscho** [comment]
> @benscho you can try my fork repo https://github.com/Bunhouth/react-native-video-processing
> I'm not sure, if it work for you or not but it work fine on my project with latest RN version.

Hey BunHouth, thanks for sharing your repo! I have to agree with @mladibejn, though... I played around with it a bit and I wasn't able to get it to compile in my project. It looks promising, though, Could you provide a little guidance?

Thanks!

**Comment by BunHouth** [comment]
@mladibejn  @benscho  thanks you for your feedback.
I have made an example project. So you can check it [here](https://github.com/BunHouth/react-native-video-processing/blob/master/RNVideoProcessingDemo). it can help to solve your problem.
Here is my machine environment
OSX: 10.15.3
Xcode: 11.3.1
Yarn: 1.16.0
Node: v10.15.3
react-native-cli: 2.0.1

Thanks

**Comment by benscho** [comment]
> @mladibejn @benscho thanks you for your feedback.
> I have made an example project. So you can check it [here](https://github.com/BunHouth/react-native-video-processing/blob/master/RNVideoProcessingDemo).
> Here is my machine environment
> OSX: 10.15.3
> Xcode: 11.3.1
> Yarn: 1.16.0
> Node: v10.15.3
> react-native-cli: 2.0.1
> 
> Thanks

Hey BunHouth, thanks for that! I think I understand how to use your code now. I'll get to work on it and post the results. Thanks again!

**Comment by benscho** [comment]
I'll go ahead and close this. After playing around with it more I'm quite satisfied with @BunHouth's code. All I had to do was uncomment a few GPUImage includes after copying over his files. 

It would be nice if I could figure out why I was getting the error in the first place, but it would take someone more familiar with iOS development than myself to explain that!

**Comment by ahmadzahidglixen** [comment]
Hi @benscho Thanks for your help so far.
Could you guide me on this:
https://github.com/shahen94/react-native-video-processing/issues/283?

I'm really stuck here.
