### ISSUE TITLE
error: error opening input file 'myproj/node_modules/react-native-video-processing/ios/RNVideoProcessing-Bridging-Header.h' (No such file or directory)

### ISSUE THREAD

**Issue by ahmadzahidglixen** [shahen94/react-native-video-processing#283]
### Current Behavior

Cannot build the project on iOS, I've tried configuring following the video. Step by step.
Followed many threads, but couldn't find any workable solution.
Still get this error:

error: error opening input file 'myproj/node_modules/react-native-video-processing/ios/RNVideoProcessing-Bridging-Header.h' (No such file or directory) 

I'm really stuck here, help anyone?
### Your Environment

|            software            | version
| ------------------------------ | -------
| react-native-video-processing  |  1.20.0
| react-native                   |  0.61.2
| node                           |

**Comment by xlogix** [comment]
I had the exact issues. Follow this thread: https://github.com/shahen94/react-native-video-processing/issues/276

**Comment by ahmadzahidglixen** [comment]
@xlogix I was able to configure the project on iOS successfully, thank you.

The issue I'm facing now is:
TypeError: Cannot read property 'compress' of undefined

I don't know exactly what is wrong.
Since the very same code is working on Android.

Any help?

**Comment by ahmadzahidglixen** [comment]
This particular issue was resolved using 
Bunhouth's fork.

However there are other issues.

**Comment by xlogix** [comment]
Please send a PR to my fork so we van resolve that issue too.
