### ISSUE TITLE
[iOS] TypeError: Cannot read property 'compress' of undefined

### ISSUE THREAD

**Issue by ahmadzahidglixen** [shahen94/react-native-video-processing#284]
### Current Behavior
` ProcessingManager.compress(path, compressoptions) `
Calling the compress method gives this error on iOS.
However when I call the same method on Android it works fine.

### Your Environment

|            software            | version
| ------------------------------ | -------
| react-native-video-processing  |  Bunhouth/react-native-video-processing
| react-native                   |  0.61.2

**Comment by Jkiten** [comment]
Hello, I am in the same situation right now. Anyone solve it?

**Comment by coschmit** [comment]
> Hello, I am in the same situation right now. Anyone solve it?

nope :( 
If someone found solution ^^

**Comment by BunHouth** [comment]
> ### Current Behavior
> `ProcessingManager.compress(path, compressoptions)`
> Calling the compress method gives this error on iOS.
> However when I call the same method on Android it works fine.
> 
> ### Your Environment
> software	version
> react-native-video-processing	Bunhouth/react-native-video-processing
> react-native	0.61.2

I don't see any issue.
check example here https://github.com/BunHouth/react-native-video-processing/blob/master/RNVideoProcessingDemo/VideoProcessing.js#L59

**Comment by ahmadzahidglixen** [comment]
@BunHouth  Thanks for the help 
Got this one resolved comparing with the example.
