### ISSUE TITLE
Issue trimming portrait videos rotates the videos to landscape on IOS

### ISSUE THREAD

**Issue by electricfeel1979** [shahen94/react-native-video-processing#285]
### Current Behavior
When I recently updated the react native to 0.62.2 from 0.61.5, I started to have this issue with portrait videos being rotated to landscape and this only happens only on IOS. I am using the ProcessingManager.trim function.

### Expected Behavior
Trim the videos but the portrait videos shout not be rotated to landscape

### Your Environment

|            software            | version
| ------------------------------ | -------
| react-native-video-processing  |  1.20.0
| react-native                   |  0.62.2
| node                           | 12.13.1

**Comment by electricfeel1979** [comment]
okay so with zero knowledge in swift, and my first time opening a swift file. I was able to create a quick fix for this issue which honestly I don't totally understand entirely, just copied some bits of codes from the crop function and boomerang and saw there about a quick fix with videos rotating.

`
        let track = composition.addMutableTrack(withMediaType: .video, preferredTrackID: Int32(kCMPersistentTrackID_Invalid))


        let videoOrientation = self.getVideoOrientationFromAsset(asset: asset)

        if ( videoOrientation == .up || videoOrientation == .down ) {
          //fix issue where boomerang effect on main camera video is rotated 90 degrees
          var transforms: CGAffineTransform?
          transforms = track?.preferredTransform
          transforms = CGAffineTransform(rotationAngle: 0)
          //detect camera type
            transforms = transforms?.concatenating(CGAffineTransform(rotationAngle: CGFloat(90.0 * .pi / 180)))
            track?.preferredTransform = transforms!
          //end of fix
        }
`

that in RNVideoTrimmer.swift on the function trim

**Comment by gmansour09** [comment]
> okay so with zero knowledge in swift, and by desperate call. I was able to create a quick fix for this issue which honestly I don't totally understand entirely, just copied some bits of codes from the crop function and boomerang and saw there about a quick fix with videos rotating.
> 
> ```
>        let track = composition.addMutableTrack(withMediaType: .video, preferredTrackID: Int32(kCMPersistentTrackID_Invalid))
> 
>         let videoOrientation = self.getVideoOrientationFromAsset(asset: asset)
> 
>         if ( videoOrientation == .up || videoOrientation == .down ) {
>           var transforms: CGAffineTransform?
>           transforms = track?.preferredTransform
>           transforms = CGAffineTransform(rotationAngle: 0)
> 
>             transforms = transforms?.concatenating(CGAffineTransform(rotationAngle: CGFloat(90.0 * .pi / 180)))
>             track?.preferredTransform = transforms!
>         }
> ```
> 
> that in RNVideoTrimmer.swift on the function trim

electricfeel1979  your a life saver I spent all day trying to figure this out. Works great thanks!

**Comment by electricfeel1979** [comment]
> > okay so with zero knowledge in swift, and by desperate call. I was able to create a quick fix for this issue which honestly I don't totally understand entirely, just copied some bits of codes from the crop function and boomerang and saw there about a quick fix with videos rotating.
> > ```
> >        let track = composition.addMutableTrack(withMediaType: .video, preferredTrackID: Int32(kCMPersistentTrackID_Invalid))
> > 
> >         let videoOrientation = self.getVideoOrientationFromAsset(asset: asset)
> > 
> >         if ( videoOrientation == .up || videoOrientation == .down ) {
> >           var transforms: CGAffineTransform?
> >           transforms = track?.preferredTransform
> >           transforms = CGAffineTransform(rotationAngle: 0)
> > 
> >             transforms = transforms?.concatenating(CGAffineTransform(rotationAngle: CGFloat(90.0 * .pi / 180)))
> >             track?.preferredTransform = transforms!
> >         }
> > ```
> > 
> > 
> > that in RNVideoTrimmer.swift on the function trim
> 
> @electricfeel1979 your a life saver I spent all day trying to figure this out. Works great thanks!

@gmansour09 I updated the code, since the previous fix was still rotating unusual video orientations. That one fixed all of the issues. This is just a temporary fix, I have no knowledge with swift. I hope someone will be able to fix this officially.

**Comment by wehriam** [comment]
See #299

**Comment by shahen94** [comment]
PR is merged, releasing new version.

**Comment by electricfeel1979** [comment]
Just saw that this was solved, and my code is the official fix :)

**Comment by krupalikevadiya** [comment]
It is not worked for all type of videos..can you please suggest me any other way to solve it.
