### ISSUE TITLE
Can't upload to server 

### ISSUE THREAD

**Issue by akug17** [shahen94/react-native-video-processing#288]
ProcessingManager giving me this = file:///data/user/0/com.cirkle/cache/471afa27-2f4d-42a3-bb44-01856e938930-screenshot7605220013603038720.mp4 
as a temp video, but when i am trying to upload this to the server it throws error

**Comment by shahen94** [comment]
HI @akug17 
File exists in your filesystem, probably your uploaded can't reach to it.
Check the docs of your uploader.

Thanks

**Comment by akug17** [comment]
it works now idk what i was doing wrong but after re writing the complete code it works now. This library is a life saver man !
