### ISSUE TITLE
Help installing the library

### ISSUE THREAD

**Issue by matamicen** [shahen94/react-native-video-processing#298]
Hi guys,

Sorry but I don't know how it works, I had Installed react-native-video-processing, no problem.
Do I have to do something with -> **Update ffmpeg binaries instructions** if I want just to compress and Trim video on Android and iOS? I don't want to view the video on the APP.
Can somebody guide to me How to do th ffmpeg steps? 

Thanks.
Matt.

**Comment by siddharth-kt** [comment]
How it worked for you ?

**Comment by pulbee** [comment]
It didn't.
