### ISSUE TITLE
Failing to trim video ("operation is not supported for this media")

### ISSUE THREAD

**Issue by flybayer** [shahen94/react-native-video-processing#30]
I'm trying to trim a video using `VideoPlayer.trim()`, but it keeps failing with this error:
```
Failed: Optional(Error Domain=AVFoundationErrorDomain Code=-11838 "Operation Stopped" 
UserInfo={NSUnderlyingError=0x170656cb0 {Error Domain=NSOSStatusErrorDomain Code=-12109 "(null)"}, 
NSLocalizedFailureReason=The operation is not supported for this media., 
NSLocalizedDescription=Operation Stopped})
```
I've tried different configs and videos with no success, including linking one video to the player and another to `trim()`. However, `<VideoPlayer>` can play the video just fine.

Maybe this isn't an issue with this library, but I'm new to iOS video processing (and RN in general) and figured I'd start here.

*Are there special permissions or settings I need in my app for this?*

Thanks for any help!! 

### The main sample video I'm trying to trim:

http://www.sample-videos.com/video/mp4/720/big_buck_bunny_720p_5mb.mp4

### My Code:

```jsx
export default class App extends Component {
  trimVideo = () => {
    const options = {
      startTime: 0,
      endTime: 5,
    };
    this.videoPlayerRef.trim(require('./videoFile.mp4'), options)
      .then((newSource) => console.log(newSource))
      .catch(console.warn);
  }

...

  render() {
    return (
      <View style={{ flex: 1 }}>
        <View style={{ flex: 3 }}>
          <VideoPlayer
            ref={ref => this.videoPlayerRef = ref}
            play={true}
            replay={true}
            source={require('./videoFile.mp4')}
            playerWidth={300}
            playerHeight={500}
            style={{ backgroundColor: 'black' }}
            onChange={({ nativeEvent }) => console.log('change:', { nativeEvent })}
          />
        </View>
        <View style={{ flex: 1 }}>
          <TouchableOpacity
            onPress={this.trimVideo}
            style={{backgroundColor: 'yellow'}}
          >
            <Text>Trim & Save</Text>
          </TouchableOpacity>
        </View>
      </View>
    )
  }
}
```

**Comment by shahen94** [comment]
@flybayer can you try please to trim video from bundle, or from assets-library.
I'm not sure that you can trim video just requiring it.
https://github.com/shahen94/react-native-video-processing/blob/master/ios/RNVideoProcessing/RNVideoTrimmer/RNVideoTrimmer.swift#L252

**Comment by flybayer** [comment]
Aw, yes! I added a video picker and now can trim videos from the assets-library.

Thanks!
