### ISSUE TITLE
Large file size Video not compressing 

### ISSUE THREAD

**Issue by ahmadzahidglixen** [shahen94/react-native-video-processing#308]
### Current Behavior

The library is working fine for smaller size of videos. If I try to compress a larger size video ( 317 MB ) in my case.
It doesn't respond.

### Expected Behavior

Should compress the larger files, that is where the compression is needed the most.

### Your Environment

|            software            | version
| ------------------------------ | -------
| react-native-video-processing  |  Bunhouth/react-native-video-processing
| react-native                   |  ^0.61.2
| node                           | v12.4.0

**Comment by walvekarnikhil** [comment]
@ahmadzahidglixen 
Getting the same error, did you find any solution or root cause?

**Comment by ahmadzahidglixen** [comment]
@walvekarnikhil no, I haven't found any root cause of behaviour.
Had to switch change library for compressing videos.

Now i'm using:
https://www.npmjs.com/package/react-native-audio-video-tools
that uses ffmpeg at the core.
