### ISSUE TITLE
[Error: Crop error: failed. java.io.IOException: Cannot run program "/data/app/com.packagename-nKQdhhg77r272z83uYjDug==/lib/arm64/libffmpeg.so": error=2, No such file or directory]

### ISSUE THREAD

**Issue by ahmedbhesaniya97** [shahen94/react-native-video-processing#314]
### Current Behavior
I'm using this library for cropping video,as it work prefects in debug build but it throws error while in production build.
[Error: Crop error: failed. java.io.IOException: Cannot run program "/data/app/com.packagename-nKQdhhg77r272z83uYjDug==/lib/arm64/libffmpeg.so": error=2, No such file or directory]

### Expected Behavior
It will be work perfect in production as well

### Your Environment
react-native-video-processing - 2.0.0

**Comment by ChintanRajpara** [comment]
Same issue

**Comment by chuchden** [comment]
Same issue here too

**Comment by murugeshnadar** [comment]
same issue here, Please do update if anyone got solution

**Comment by ahmedbhesaniya97** [comment]
@chuchden @murugeshnadar You are gettinng this error with android bundle ?

**Comment by Alejov0** [comment]
Im getting this error after uploading the .aab file to the store. Any updates?

**Comment by murugeshnadar** [comment]
I was getting the same error.
The .aab file uploaded to the play console when downloaded to the device for internal testing does not uncompress the native library file hence we are getting the error.
I added the below code to make it work and now my APK works on my device and I am able to use ProcessManager
I added android:extractNativeLibs = "true" to AndroidManifest.xml file (This change made the code work locally in development)
android.bundle.enableUncompressedNativeLibs=false (This change made the code to work for APK downloaded using the play console for internal testing)

**Comment by Alejov0** [comment]
Thank you for the response, I'll try it tomorrow and i will let you know if it works for me, thanks👌

**Comment by Alejov0** [comment]
@murugeshnadar Thank you, it worked like a charm.

**Comment by medmo7** [comment]
If any one is wondering where to add android:extractNativeLibs = "true"  it's in application block:

```xml <application android:extractNativeLibs = "true"```

At least it work for me.
