### ISSUE TITLE
Bugs in Xcode 12

### ISSUE THREAD

**Issue by jackyleehong** [shahen94/react-native-video-processing#316]
Failed to build when tested on Xcode 12

in ffmpeg/lib/libavcodec.a(aacencdsp.o), building for iOS simulator, but linking in object file built for free standing, for architecture x86_64

|            software            | version
| ------------------------------ | -------
| react-native-video-processing  |  2.0.0
| react-native                   |  0.61.4
| node                           |14.0

**Comment by jackyleehong** [comment]
It seems like there is a need to update the ffmpeg package to resolve this issue.

**Comment by matamicen** [comment]
@jackyleehong how are you? Did you find any solution to this situation? 

Thanks!

**Comment by jackyleehong** [comment]
After upgrade to RN 0.63.3, the issue seems already not there, but I am experiencing some issue on android:Exception in native call from JS
