### ISSUE TITLE
Compression not working when downloading app from google play

### ISSUE THREAD

**Issue by benscho** [shahen94/react-native-video-processing#317]
### Current Behavior

When I run my android app locally, either on a test device or simulator, I'm able to properly compress videos. This works on development or release mode. 

However, when I submit the working build to Google Play for an internal test, it no longer works. The compression fails. I'm trying to upload files and then submit them to a database, and the database is never hit (from the version downloaded from the google play store).

### Expected Behavior

I should still be able to compress videos after submitting the app to Google

### Your Environment

|            software            | version
| ------------------------------ | -------
| react-native-video-processing  |  latest (pulled from github)
| react-native                   |  0.60.0
| node                           |

**Comment by chuchden** [comment]
I have this issue too.
On local work fine, but download from play store is not working
[processingmanager.crop is not working]
Waiting for solution

**Comment by chuchden** [comment]
Error Crop Failed... Can not run program..........
https://gitmemory.com/issue/shahen94/react-native-video-processing/273/657013161

**Comment by Alejov0** [comment]
Same here, any updates?

**Comment by Alejov0** [comment]
This [comment ](https://github.com/shahen94/react-native-video-processing/issues/314#issuecomment-716412764)helped me a lot, maybe you should try it.

**Comment by shahen94** [comment]
Closing out https://github.com/shahen94/react-native-video-processing/issues/317#issuecomment-716803882
