### ISSUE TITLE
AccessibilityResources.bundle not found

### ISSUE THREAD

**Issue by James-revans** [shahen94/react-native-video-processing#319]
<img width="527" alt="Screen Shot 2020-11-01 at 10 07 17 PM" src="https://user-images.githubusercontent.com/42704409/97835260-9ecb7600-1c8e-11eb-8aac-6a4e74b7683e.png">

### Current Behavior

Followed along with video exactly for ios implementation and when running a build in xcode I keep getting this error. I've tried a pod install like it suggests but that hasn't helped.

### Expected Behavior

Everything else passes and this is the only build that fails, so hopefully I won't encounter the same errors it seems everyone else is encountering.

Also, I'm a web dev and not as familiar with ios development so this could be a simple thing, but thought I'd ask. 

Thanks!

### Your Environment

|            software            | version
| ------------------------------ | -------
| react-native-video-processing  | 2.0.0
| react-native                   | 0.63.3
| expo                           | 39.0.2
| node                           | 12.13.0

**Comment by cedced19** [comment]
I have the [same issue](https://stackoverflow.com/questions/64701697/ios-unable-to-archive-rn-0-63-3-accessibilityresources-bundle-not-found). I think it is notdue to `react-native-video-processing`. Did you find a solution ?

**Comment by James-revans** [comment]
I agree, but I thought I'd post here just in case anyone had some insight. 
I have not found a solution yet. I think I might have to look into ios development a little more to find out what to do

**Comment by shahen94** [comment]
This is not a current lib issue. It's related to react-native. Closing this out.
https://github.com/facebook/react-native/issues/30335
