### ISSUE TITLE
 TypeError: undefined is not an object (evaluating 'ProcessingUI.Constants')

### ISSUE THREAD

**Issue by LiaqatSaeed** [shahen94/react-native-video-processing#320]
### Current Behavior
Getting following errors on build of project

Require cycles are allowed, but can result in uninitialized values. Consider refactoring to remove the need for a cycle.
**ERROR**    TypeError: undefined is not an object (evaluating 'ProcessingUI.Constants')
**ERROR**    Invariant Violation: Module AppRegistry is not a registered callable module (calling runApplication)
**ERROR**    Invariant Violation: Module AppRegistry is not a registered callable module (calling runApplication)

### Expected Behavior
Video processing module should work properly

Getting erros on IOS

|            software            | version
| ------------------------------ | -------
| react-native-video-processing  |  2.0.0
| react-native                   |  0.63.2
| node                           |

**Comment by eshraj302** [comment]
Yes, i am having the same issue on **IOS**.

**Comment by LiaqatSaeed** [comment]
> Yes, i am having the same issue on **IOS**.

Any Solution you got for this?

**Comment by eshraj302** [comment]
> > Yes, i am having the same issue on **IOS**.
> 
> Any Solution you got for this?

Sadly no...still same issue persists

**Comment by LiaqatSaeed** [comment]
@shahen94 Can you please look into this issue?

**Comment by eshraj302** [comment]
Hi @LiaqatSaeed , Please try linking the package manually, that solved the issue for me, now it's working fine.

**Comment by LiaqatSaeed** [comment]
> Hi @LiaqatSaeed , Please try linking the package manually, that solved the issue for me, now it's working fine.

can you please share your steps?

**Comment by eshraj302** [comment]
I followed the official docs for linking the ios library, you can also look at the video for ease of understanding: https://www.youtube.com/watch?v=HRjgeT6NQJM&feature=youtu.be
