### ISSUE TITLE
Trimmer crashers the android app

### ISSUE THREAD

**Issue by avidhaus-adeel** [shahen94/react-native-video-processing#326]
### Current Behavior
Trimmer is working in debug mode but crasher the app in Release mode in android

### Your Environment
windows

|            software            | version
| ------------------------------ | -------
| react-native-video-processing  |  ^2.0.0
| react-native                   |  0.63
| node                           | 12.14.1

**Comment by jackyleehong** [comment]
I manage to solve this issue by disable the Proguard in Android /  manually add the proguard rule.

**Comment by pmella16** [comment]
> I manage to solve this issue by disable the Proguard in Android / manually add the proguard rule.

hello, i have the same problem, you can help me to configure the proguard rules

**Comment by codefromhimanshu** [comment]
> I manage to solve this issue by disable the Proguard in Android / manually add the proguard rule.

Please help me solve this issue. added

`-keep class com.shahenlibrary.Trimmer.* {*;}
`
to proguard still not able to fix this issue.
