### ISSUE TITLE
Video Trim Not working in android aab build?

### ISSUE THREAD

**Issue by mplsnikhilmonga** [shahen94/react-native-video-processing#335]
### Your Environment

|            software            | version
| ------------------------------ | -------
| react-native-video-processing  |  
| react-native                   |  
| node                           |

**Comment by crava-logico-srl** [comment]
We've noticed that the runtime of the aab bundle could not find the libffmpeg.so in the jniLibs folder.
Try add _android.bundle.enableUncompressedNativeLibs=false_ in gradle.properties.
