### ISSUE TITLE
Problem with source props && Can you add some example of this component

### ISSUE THREAD

**Issue by RZulfikri** [shahen94/react-native-video-processing#34]
Hi, i'm trying this component but i always get an error with source props. I already copy source code from readme, but still got an error. Maybe if you dont mind. can you add full example code.? and how if i wanna edit video with uri ?

thanks

**Comment by shahen94** [comment]
@RZulfikri on which platform did you test it ? IOS or Android

**Comment by RZulfikri** [comment]
I'm using android.
I got this error :
![screenshot_2017-02-21-14-23-03](https://cloud.githubusercontent.com/assets/24998199/23154696/c574b5d4-f841-11e6-8e4e-e4ceb2597e68.png)

**Comment by shahen94** [comment]
Android version is very young, and currently have different API, I had no time to update readme for android, I'll push updates in end of this week.

Stay tuned, thanks !

**Comment by RZulfikri** [comment]
oke thankyou..

**Comment by shahen94** [comment]
@RZulfikri try the latest version, #35 fixed this issue
So i'm going to close this issue, feel free to reopen this issue if your issue will not be solved
