### ISSUE TITLE
setDataSource failed: status = 0xFFFFFFFF

### ISSUE THREAD

**Issue by pm-sharma** [shahen94/react-native-video-processing#341]
### Your Environment

|            software            | version
| ------------------------------ | -------
| react-native-video-processing  |  ^2.0.0
| react-native                   |  0.64.0

**Comment by pm-sharma** [comment]
For me it was in case I am loading the local file from project folder. In other conditions(From mobile gallery or recorded video/images) working fine.

**Comment by viprocket1** [comment]
Hey, Did you solve it? could you please share?
