### ISSUE TITLE
Compression Really Slow On Android

### ISSUE THREAD

**Issue by siddharth-kt** [shahen94/react-native-video-processing#343]
### Current Behavior
It is really slow to compress video on Android (for 1 minute video it takes 15 - 25 seconds), whereas on apps like WhatsApp compression is really fast.

### Expected Behavior
It should take less than 5 second time for compression. Please tell me
- If i am doing anything wrong or
- Any solution for this problem.

### My Environment
Device Company  ->  Vivo
Android  -> 11
Funtouch OS  ->  10.5

|            software            | version
| ------------------------------ | -------
| react-native-video-processing  |  ^2.0.0
| react-native                   |  0.64.2
| node                           |  v14.17.0

**Comment by shahen94** [comment]
@siddharth-kt FFMPEG is a slow library, the main issue comes from there. You shouldn't feel this issue on iOS since we not used it there

**Comment by siddharth-kt** [comment]
> @siddharth-kt FFMPEG is a slow library, the main issue comes from there. You shouldn't feel this issue on iOS since we not used it there

Yes, thanks for answering 🙂, so for android currently there is no solution to speed-up compression.
