### ISSUE TITLE
Error when running application in expo environment

### ISSUE THREAD

**Issue by jsindos** [shahen94/react-native-video-processing#356]
I'm getting the following error when running the project in an expo environment with the first example usage code from readme.md:

```
2022-02-10 15:14:28.707610+1100 expoeject[5429:23036] [native]
Error setting property 'source' of RNTrimmerView with tag #5:
Exception thrown while executing UI block:
CALayer bounds contains NaN: [0 0; nan 20].
Layer:
<CALayer:0x6000018fc1e0;
  position = CGPoint (0 0);
  bounds = CGRect (0 0; 0 0);
  delegate = <UIView: 0x7faeb681d7f0;
    frame = (0 0; 0 0);
    layer = <CALayer: 0x6000018fc1e0>
  >;
  allowsGroupOpacity = YES;
>
```

Does anyone else have it working successfully in a bare workflow expo environment?

### Your Environment

|            software            | version
| ------------------------------ | -------
| react-native-video-processing  |  ^2.0.0
| react-native                   |  0.64.3
| node                           | 14.16.1
| expo | ~44.0.2
| Xcode | 13.2.1

**Comment by jsindos** [comment]
I hadn't changed the `source` lines in the example code, changed them and it's working now.

**Comment by mattmarcello** [comment]
@jsindos did you need to eject to get this running in expo?
