### ISSUE TITLE
Cannot read property 'compress' of null

### ISSUE THREAD

**Issue by savataqe1** [shahen94/react-native-video-processing#364]
Hello everyone,i am facing this issue when i try to compress my videos.

`Cannot read property 'compress' of null`

1. Platform:Android
2. Device: Pixel 4 XL
3. RN Version: "0.68.0",
4. react-native-video-processing Version:"^2.0.0",
5. gradle Version:gradle-7.3.3

**Comment by Logicbuzz04** [comment]
video_path.compress();

please check video_path.

otherwise send your code
