### ISSUE TITLE
Feature: Allow using library API's without mounting <VideoPlayer>

### ISSUE THREAD

**Issue by flybayer** [shahen94/react-native-video-processing#37]
I'm using this library to trim videos, but I don't need the `<VideoPlayer>` component. I'd love to use the API's directly without mounting this component.

Thanks! :)

**Comment by shahen94** [comment]
@flybayer you are able to edit video file without mounting VideoPlayer component.
See what we did in VideoPlayer.js file

https://github.com/shahen94/react-native-video-processing/blob/master/lib/VideoPlayer/VideoPlayer.ios.js#L6

You can import `RNVideoTrimmer` from native modules and use as you want
