### ISSUE TITLE
unreported exception IOException; must be caught or declared to be thrown in RN 0.70.0 and target and compile is 33 for android

### ISSUE THREAD

**Issue by chetanacquaintsoft** [shahen94/react-native-video-processing#372]
### Your Environment

|            software            | version
| ------------------------------ | -------
| react-native-video-processing  |  1.7.2
| react-native                   |  0.70.0
| node                           | 16.17.0

unreported exception IOException; must be caught or declared to be thrown in RN 0.70.0 and target and compile is 33 for android

**Comment by jamiembrown** [comment]
Did anyone find a workaround or hack for this at all?

**Comment by mustneerar7** [comment]
minSdkVersion = 21
compileSdkVersion = 31
targetSdkVersion = 33

worked for me.

**Comment by pritsawa** [comment]
https://www.youtube.com/watch?v=VqCdCLn9HQI

**Comment by denisbevilacqua** [comment]
> Did anyone find a workaround or hack for this at all?

I have opened a [PR](https://github.com/shahen94/react-native-video-processing/pull/398) for this!

**Comment by jamiembrown** [comment]
> I have opened a [PR](https://github.com/shahen94/react-native-video-processing/pull/398) for this!

Thanks so much Denis! I'll take a look in our next release!
