### ISSUE TITLE
Problem with source, no view loaded.

### ISSUE THREAD

**Issue by RZulfikri** [shahen94/react-native-video-processing#38]
I'm trying the usage example from readme, i use 

```
<VideoPlayer
....
source={{ uri: this.props.uri }}
....
/>
```
and also for Trimmer
```
<Trimmer
....
source={{ uri: this.props.uri }}
....
/>
```

but, i got warning 'Failed prop type: Invalid prop source supplied to VideoPlayer' and no view loaded, also same for Trimmer . i got this in ios and android. did i miss something ?

then i'm trying using ` source={require('./video.mp4')}` no error and no view loaded.

if you don't mind, would you add an example ?

thx

**Comment by shahen94** [comment]
@RZulfikri just add source 
https://github.com/shahen94/react-native-video-processing/blob/master/lib/VideoPlayer/VideoPlayer.ios.js#L10

```
<VideoPlayer
....
source={this.props.uri}
....
/>
```

**Comment by shahen94** [comment]
https://github.com/shahen94/react-native-video-processing/commit/88ce49ba01f43c3d5cb5af76da38b73554a1761b

**Comment by RZulfikri** [comment]
already try that solution, but i got nothing in my view, it only litle red in left corner..

![simulator screen shot mar 2 2017 7 00 17 am](https://cloud.githubusercontent.com/assets/24998199/23487022/1d08d340-ff16-11e6-85dd-a4a6b03c72eb.png)

and my code :
<img width="732" alt="screen shot 2017-03-02 at 7 02 21 am" src="https://cloud.githubusercontent.com/assets/24998199/23487051/3e983fb4-ff16-11e6-8fa8-4f0960b04cde.png">

did i miss something ?

**Comment by shahen94** [comment]
Can you please copy and past your source URI here, also please give me more details on which platform did you checked it, on which rn version do you use

**Comment by shahen94** [comment]
Can you please copy and past your source URI here, also please give me more details on which platform did you checked it, on which rn version do you use

**Comment by RZulfikri** [comment]
actually i use file from camera roll/device. I use image picker component, so the URI may look like "/Users/lembah8/Library/Developer/CoreSimulator/Devices/B187BB61-5580-423A-98BC-1E1D0F3D5FA2/data/Containers/Data/Application/D82AA33C-E5B0-467A-B4BD-B2F57E7EDBA4/tmp/trim.72D3B914-8A93-473D-8158-4046026A7C34.MOV"

i try it on IOS, using react-native 4.0

**Comment by shahen94** [comment]
seems like you linked library not correctly, check `How to setup` section

**Comment by flybayer** [comment]
I think when the path is like yours, @RZulfikri, you need to prepend `file://` to the path.

**Comment by RZulfikri** [comment]
@shahen94 already try setup xcodeproj by following video tutorial for  twice, but still got same problem..  @flybayer already try but still same..  

can you add some example project ?

thanks.

**Comment by RZulfikri** [comment]
@shahen94 when i try on android it work 

This the view when i try in ios and android.

| Android | IOS |
| ----- | ----- |
| ![screenshot_2017-03-03-09-53-32-851_id veedy mobile](https://cloud.githubusercontent.com/assets/24998199/23536444/810e4b22-fff7-11e6-8bfc-8d78a2e69ae7.png) | ![simulator screen shot mar 3 2017 9 53 39 am](https://cloud.githubusercontent.com/assets/24998199/23536453/8c91f3ae-fff7-11e6-9a43-f1f818358a96.png) |

i guess i missing something when setup IOS but i dont know what. For information, my project didnt have "ProjectName-Bridging-Header.h" so i create one and add some code from your video. Did the problem because of that ?

**Comment by shahen94** [comment]
@RZulfikri you are using reacts natives images picker right ?

**Comment by RZulfikri** [comment]
@shahen94  yup..

**Comment by shahen94** [comment]
Well, it as result gives you object right, pass `origUrl` to source

**Comment by RZulfikri** [comment]
still same, i got uri like this "file:///Users/lembah8/Library/Developer/CoreSimulator/Devices/B187BB61-5580-423A-98BC-1E1D0F3D5FA2/data/Containers/Data/Application/5020CE67-D857-4C72-9166-C13D7060452E/tmp/trim.0B0D6057-ED5D-40EA-A8D0-FEDCE281F0CA.MOV"

**Comment by shahen94** [comment]
@RZulfikri `origUrl` gives you url from assets library, it should start with `assets-library?` .

**Comment by RZulfikri** [comment]
@shahen94 so i should try that on device ? because assets-library only for devices ?

**Comment by shahen94** [comment]
@RZulfikri not only, i used it on simulator

**Comment by shahen94** [comment]
@RZulfikri Definitely you're linked the library not correctly. React-native shows red border around unrecognized view.

**Comment by RZulfikri** [comment]
@shahen94 what should i do then ?

**Comment by shahen94** [comment]
@RZulfikri check chrome console, there should but an error,  remove library from project and follow the video, and do all what it shows

**Comment by RZulfikri** [comment]
@shahen94 ok thank you, i will try..

**Comment by RZulfikri** [comment]
yeah you right. Already remove library and re-add library but still got this issue..

<img width="1680" alt="screen shot 2017-03-05 at 5 20 57 pm" src="https://cloud.githubusercontent.com/assets/24998199/23586489/51d0490a-01c8-11e7-8ab5-d8a6e48c703f.png">

**Comment by RZulfikri** [comment]
@shahen94 i guess it because failed import method..  based on tutorial video, i must import RVVideoProcessing like `#import "RNVideoProcessing.h"` and it look same at "RNVideoProcessing.h" `#import "RNTrimmerView.h"` and i'm trying to add file directory before file name, but still got that error..   And thanks for your response

**Comment by RZulfikri** [comment]
@shahen94 i already follow step from readme and step from video, but still error..

**Comment by shahen94** [comment]
@RZulfikri do you still have this issue ?

**Comment by RZulfikri** [comment]
@shahen94 For IOS ? yes..

**Comment by shahen94** [comment]
Well, let's try to link android manually.
for the first unlink library
```sh
$ react-native unlink react-native-video-processing
```

after that

Open up android/app/src/main/java/[...]/MainActivity.java
Add `import com.shahenlibrary.RNVideoProcessingPackage;` to the imports at the top of the file
Add new  `new RNVideoProcessingPackage()`  to the list returned by the getPackages() method
Append the following lines to android/settings.gradle:
```
include ':react-native-video-processing'
project(':react-native-video-processing').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-video-processing/android')
```

Insert the following lines inside the dependencies block in android/app/build.gradle:
```
    compile project(':react-native-video-processing')
```

And then link iOS version again as demonstrated in the video.

https://github.com/shahen94/react-native-video-processing/issues/48

**Comment by RZulfikri** [comment]
@shahen94 thanks
