### ISSUE TITLE
Trimmer glitching

### ISSUE THREAD

**Issue by JBerendes** [shahen94/react-native-video-processing#40]
Trimmer glitches when trying to grab the start, end, or current position of trimmer.
Is anyone else having this issue? I'll see if I can get a recording.

**Comment by shahen94** [comment]
@JBerendes thanks for reporting this issue.
Can you please give us more details ? Where it's happening on iOS or on Android, your react-native version and that's piece of code.

**Comment by JBerendes** [comment]
Nevermind. It's so strange it just started working out of nowhere. I had been fussing with it for a few weeks. I'm on iOS and running completely up to date. I'll post a video if I run into any more anomalies
