### ISSUE TITLE
Increase tap surface for start and end handles

### ISSUE THREAD

**Issue by JBerendes** [shahen94/react-native-video-processing#41]
The trimmer works if can tap and get ahold of the shaded area to the left of the start or to the right of the end. When it starts it's likely at 0. Obviously grabbing something with 0 width is hard. It takes about 3 to 5 tries to get ahold of the left trimmer and even more for the right one. Is there a way to increase the hitslop of these? Would anyone else find it worthwhile to add a handleHitslop property?

**Comment by JBerendes** [comment]
i can help if you want to point me at a good place to start looking. If you would rather do it I can help with the pull request.

**Comment by shahen94** [comment]
@JBerendes i've added 20 points hitSlop around right and left corners, so it should help

**Comment by JBerendes** [comment]
testing now

**Comment by JBerendes** [comment]
It doesn't seem to have been solved.  The video starts several seconds after I have been trying to grab the starting trimmer ... Then when I'm moving it more fluidly it's because I'm grabbing the shaded area.
![mar-13-2017 12-48-19](https://cloud.githubusercontent.com/assets/596925/23867892/6a4c80f6-07eb-11e7-9fac-7295efcd1679.gif)

**Comment by shahen94** [comment]
Well try to change that line which I've pointed

**Comment by JBerendes** [comment]
My thought is that the area offered as touchable is not larger than what is visible. So any touch events that occur to the left of the white start trimmer are not seen because the are outside of the parent container.

I'll try what you just mentioned. Thanks

**Comment by JBerendes** [comment]
I see, we need access to a thumbWidth prop so it can be passed to ICGVideoTrimmerView.m on smaller devices it's simply to narrow at the default value.

**Comment by shahen94** [comment]
great, look how we provide all props to JS side, in similar way you can also pass thumbsWidth prop

**Comment by JBerendes** [comment]
will do.

**Comment by shahen94** [comment]
Released https://github.com/shahen94/react-native-video-processing/releases/tag/v1.5.0

**Comment by JBerendes** [comment]
looks good.
