### ISSUE TITLE
Feature: Add watermark-type overlay to videos

### ISSUE THREAD

**Issue by flybayer** [shahen94/react-native-video-processing#43]
I need to add a watermark to my videos. If you're ok with this feature being added, @shahen94, I'll submit a PR after I finish it.

**Comment by shahen94** [comment]
@flybayer pull request is welcome, thanks !

**Comment by shahen94** [comment]
@flybayer just for notice when you'll e able to open PR ?

**Comment by flybayer** [comment]
Should be within a week. I haven't started yet but need it soon.

**Comment by shahen94** [comment]
Closing this thread due to long inactivity

**Comment by dancork** [comment]
@flybayer did you manage this?

**Comment by flybayer** [comment]
@dancork here's what I ended up using: https://github.com/flybayer/react-native-watermark/tree/bb (on the `bb` branch)
