### ISSUE TITLE
Feature: Concatenate two videos together

### ISSUE THREAD

**Issue by flybayer** [shahen94/react-native-video-processing#44]
I need to concatenate two videos together. If you're ok with this feature being added, @shahen94, I'll submit a PR after I write the code.

**Comment by shahen94** [comment]
That would be awesome to have that functiomality

**Comment by shahen94** [comment]
Closing this thread due to long inactivity

**Comment by flybayer** [comment]
Hey, I'd still love to have this! I just haven't yet had time to do it myself. :)

**Comment by shahen94** [comment]
This is pretty easy to implement on both platforms, iOS have AVFoundation which is allows to do that.
We just merged @kesha-antonov 's PR, he did great job on android side, and configured `FFPEG`, so using it i definitely sure that we can do it also for android as well.

I had no time as well to work on this project actively, i've planned to resume work in next week. But implementing concatination currently is not a my target.
