### ISSUE TITLE
Swift is not supported for static libraries

### ISSUE THREAD

**Issue by santiagovazquez** [shahen94/react-native-video-processing#48]
Hi,

I just started a project with RN and I'm trying to use this library (I'm not familiar with iOS development).

I followed the steps on the readme. I did not have the bridging header file so I followed: https://github.com/shahen94/react-native-video-processing/issues/14

XCode won't compile my project, I'm getting "Swift is not supported for static libraries" for RNVideoProcessing:
<img width="336" alt="screen shot 2017-03-18 at 1 26 02 pm" src="https://cloud.githubusercontent.com/assets/520412/24073932/830f1f4e-0bde-11e7-8779-4a04f9117bd4.png">

Thanks in advance for any help you can give me! 😃

**Comment by shahen94** [comment]
@santiagovazquez hi, please watch this video
https://github.com/shahen94/react-native-video-processing#how-to-setup-library

**Comment by santiagovazquez** [comment]
Hi @shahen94, thanks for the quick response!

If I follow the video steps it works (only iOS). But if I run the command for android set up (react-native link react-native-video-processing) it starts to show that message. Any ideas?

**Comment by shahen94** [comment]
@santiagovazquez seems like you have to link android manually, i'll write about it in readme when i'll have a chance

**Comment by shahen94** [comment]
when you're running `react-native link` it tries to link ios again, but since react-native can't link Swift library it starts fail again

**Comment by santiagovazquez** [comment]
@shahen94 Great, thanks for your help! Awesome library!

One last question, is it possible to use an URL as a source? 

My code:
```
const source = 'http://10.5.5.9:8080/videos/DCIM/100GOPRO/GOPR0238.MP4'
const options = { startTime: 5, endTime: 10 };
ProcessingManager.trim(source, options)
  .then((data) => console.log(data))
  .catch(e => console.error(e))
```

I get this error (iOS):
<img width="371" alt="screen shot 2017-03-18 at 7 37 58 pm" src="https://cloud.githubusercontent.com/assets/520412/24076564/a94d2ac8-0c12-11e7-80a9-aa49da03d055.png">
 
It works on my terminal if I do `wget 'http://10.5.5.9:8080/videos/DCIM/100GOPRO/GOPR0238.MP4'`

**Comment by shahen94** [comment]
Unfortunately no, currently you can't process remote video, VideoPlayer can play that but can't trim/compress or do some processing actions. library still working only with assets-library, do you can give a link from CameraRoll

**Comment by santiagovazquez** [comment]
hey @shahen94,

I'm not an iOS developer, so I do not understand completely what I did.

I read this post http://stackoverflow.com/questions/31383655/avassetexportsession-trim-download
and then I changed:
https://github.com/santiagovazquez/react-native-video-processing/commit/5d5755b02048c3330fc5ef0f7c5602eec0187bdb

Now I'm able to use a remote URL to cut a video (without having to download it) 😄

**Comment by shahen94** [comment]
Hey @santiagovazquez .
`asset.loadValuesAsynchronously` yea, you loaded video info asynchronously, probably that's a better idea than downloading video,  great job !  :D 

If you can put back quality options and all functionality and keep only this feature,that would be great.

**Comment by santiagovazquez** [comment]
@shahen94 let me try that and i will do a PR.
thanks for all your help!

**Comment by shahen94** [comment]
@santiagovazquez thanks for contributing !

**Comment by rpastorelle** [comment]
@shahen94 I went thru all the steps above & am still having this issue. Xcode automatically created my Bridging Header file inside the RNVideoProcessing group that I created when following the video tutorial. The contents of my file looks like this:

```
#import "RCTBridgeModule.h"
#import "RNVideoProcessing.h"
```

I've tried every single combination of imports, such as the following:

```
#import <RCTRootView.h>
#import <RCTView.h>
#import "RCTBridgeModule.h"
#import "RNVideoProcessing.h"
```

Do you have any advice for how to get this package working?

**Comment by shahen94** [comment]
Can you please copy/past the error messages ?

**Comment by rpastorelle** [comment]
I get the exact error listed above: https://cloud.githubusercontent.com/assets/520412/24073932/830f1f4e-0bde-11e7-8779-4a04f9117bd4.png

**Comment by shahen94** [comment]
@rpastorelle did you run `react-native link` ?

**Comment by rpastorelle** [comment]
@shahen94 I ran `react-native link` first & had this issue. Then I followed the video tutorial.

**Comment by shahen94** [comment]
Might @santiagovazquez can help you ?

**Comment by santiagovazquez** [comment]
@rpastorelle I recommend you to clone the repo again and follow the video tutorial

**Comment by rpastorelle** [comment]
Yeeeahhh. I did that a few times already but I'll give it another shot

**Comment by rpastorelle** [comment]
I was able to get this working! A couple notes: 

• I did *not* use `react-native link` (when I did it caused this issue). 
• I did *not* follow the video setup guide (importing that way also created this issue for me)
• *I DID* follow the manual iOS setup from the README. √

**Comment by shahen94** [comment]
So - You mean that the video demonstration doesn't help ?

Where's the problem, but right now linking this library to project is a main issue. The library we wrote on Swift, and react-native can't link Swift libraries automatically (with react-native link command). Sorry for you pain, and glad to hear that you could  get it to work

**Comment by rpastorelle** [comment]
@shahen94 Nevermind. It only worked because I didn't compile sources. As soon as I did that I have the same issue again. Still can't use the library :/

**Comment by shahen94** [comment]
@gevorg94 can you take a look what could be the problem ?

**Comment by shahen94** [comment]
I just run into steps that you provide, and have been able to compile,
Please run `react-native unlink react-native-video-processing` and then again follow to the demo video

**Comment by rpastorelle** [comment]
@shahen94 Should I run thru the video demo AND run `react-native link` or just the video demo?

**Comment by rpastorelle** [comment]
@shahen94 I have finally got this working! Life lesson: Never ever use `react-native link`. I also think I may have been having issues because I was opening the `ios/` folder instead of the `.xcodeproj` file in Xcode ¯\_(ツ)_/¯

Thanks so much for all your attention!
