### ISSUE TITLE
Borderwidth CGFloat <-> NSNumber?

### ISSUE THREAD

**Issue by BraunreutherA** [shahen94/react-native-video-processing#53]
Hi after importing the library I get this error: 

![error](https://preview.ibb.co/dDHLov/Bildschirmfoto_2017_03_30_um_14_21_20.png)

Am I importing something wrong or is this a bug?

**Comment by shahen94** [comment]
@BraunreutherA Thanks for reporting this issue. Unfortunately this is issue related to the latest PR.
https://github.com/shahen94/react-native-video-processing/pull/52

Please install 1.8.0 version instead of 1.9.0, i'll publish to npm the fix as soon as possible
