### ISSUE TITLE
Video Layer displayed twice

### ISSUE THREAD

**Issue by barbaragomes** [shahen94/react-native-video-processing#54]
Hey there,

I upgrade to the latest version but I notice that a bug (not sure if it is a bug) start happening on version 1.7.0 and up. I can see the video layer twice in the screen:

![video](https://cloud.githubusercontent.com/assets/13023284/24685629/a56cd102-1963-11e7-951c-118fa4718af5.png)

Here is my react-native code:

```
<VideoPlayer
    ref={ref => this.player = ref}
    currentTime={this.state.currentVideoTime}
    play={this.state.playing}     // default false
    startTime={this.state.start_trim}  // seconds
    endTime={this.state.end_trim}   // seconds
    replay={false}   // should player play video again if it's ended
    rotate={true}   // use this prop to rotate video if it captured in landscape mode
    source={this.props.original_asset}
    playerWidth={deviceResolution.width}
    playerHeight={0.7 * deviceResolution.height}
    style={{ backgroundColor: 'black' }}
    onChange={({ nativeEvent }) => this.playingEvent({ nativeEvent })}
    resizeMode={VideoPlayer.Constants.resizeMode.CONTAIN}
/>
```

Any ideas? That does not happen up to version 1.6.0

Thanks

**Comment by shahen94** [comment]
Hi @barbaragomes unfortunately it's a bug, still I don't know how to fix it.
You can use temp branch, there I removed `resizeMode` . 

I need some time to figure out why it's happening with landscape videos

**Comment by barbaragomes** [comment]
@shahen94  Thank you very much. I will be using the temp branch

**Comment by shahen94** [comment]
Temp branch has been merged with master and deployed to npm registry.
