### ISSUE TITLE
Error When build

### ISSUE THREAD

**Issue by choungchamnab** [shahen94/react-native-video-processing#55]
I got error when trying build. Please see in the image:

[Error](https://drive.google.com/open?id=0Byim0RqdqHbWbVB5dG5xNzByNkk)

Xcode : 8.3.1

**Comment by shahen94** [comment]
Hey @choungchamnab .
Please use `temp` branch for now until i'll fix some issues.
https://github.com/shahen94/react-native-video-processing/issues/54

**Comment by choungchamnab** [comment]
Thank You. I got success on build.
