### ISSUE TITLE
 video trim for android available?

### ISSUE THREAD

**Issue by SrengGueckly** [shahen94/react-native-video-processing#56]

**Comment by shahen94** [comment]
Yes, you can trim video in android

**Comment by SrengGueckly** [comment]
@shahen94 how ? Can u introduce me some code coz I'm a beginner with react native?

**Comment by shahen94** [comment]
Please take a look `usage` section in `README`
https://github.com/shahen94/react-native-video-processing#usage

**Comment by SrengGueckly** [comment]
@shahen94 I followed all installation instruction and I want to choose video from my device , so I changed property source in both <VideoPlayer> and <Trimmer>  to my own local path , but it doesn't work

**Comment by shahen94** [comment]
Please produce error completely

**Comment by SrengGueckly** [comment]
@shahen94 attempt to invoke virtual method int android graphics bitmap getwidth , how can I solve with this error?

**Comment by SrengGueckly** [comment]
@shahen94 the video is trimmed but I can only hear the sound without video!
