### ISSUE TITLE
Android compression timeline

### ISSUE THREAD

**Issue by olitomas** [shahen94/react-native-video-processing#58]
Is anyone working on the compression feature for Android ? I see the checkbox but was wondering if it means someone is working on it and if we can expect it anytime soon ?

**Comment by shahen94** [comment]
Hi @olitomas. I'm a busy in thes days, so can't work on it. .but PR are welcome.

**Comment by olitomas** [comment]
@shahen94 thanks for the quick reply, good to know :) Unfortunately Android stuff is not within my skillset so I wont be able to help.

**Comment by shahen94** [comment]
@olitomas android stuff little bit complicated, we should remove current trim implementation as well and replace it with Ffmpeg stuff. and after that we can do with videos what we can imagine(compress, trim, filtering, remove audio, etc.). Anyway stay tuned, probably I'll work on it in next month

**Comment by ricardofavero** [comment]
Thank you for developing this library, it's being really useful to me.
Has anyone made any progress in Android compression?

**Comment by shahen94** [comment]
Hi @ricardofavero.
Now we have FFMPEG installed in the library ecosystem - remained to call required FFMEPG command.

I can show point from where to start if there will be someone who's familiar with android development.
