### ISSUE TITLE
Can't make it work

### ISSUE THREAD

**Issue by matart15** [shahen94/react-native-video-processing#59]
After adding library to my project it displays error
```
addComponentAsRefTo(...): Only a ReactOwner can have refs. You might be adding a ref to a component that was not created inside a component's `render` method, or you have multiple copies of React loaded
```

**Comment by shahen94** [comment]
Please provide code and errors from chrome console

**Comment by matart15** [comment]
No code .
1. My project is working just fine.
2. I run `yarn add react-native-video-processing`. no `react-native link`
3. then I run `react-native run-ios`
4. after app load error on console is 
<img width="426" alt="screen shot 2017-04-26 at 15 30 08" src="https://cloud.githubusercontent.com/assets/17027219/25420911/605e332e-2a95-11e7-99cf-f474850eba9f.png">

**Comment by matart15** [comment]
Also if I remove `react-native-video-processing` from `package.json` and run `yarn`
error disappears

**Comment by shahen94** [comment]
Thanks for reporting this issue.
Seems like in your project you have 2 react versions, we need to remove react from react-native-video-processing package.json or move it to peer dependency. This should fix your issue

**Comment by matart15** [comment]
I see there is `react` in react-native-video-processing package.json.

I will try removing it.

**Comment by matart15** [comment]
@shahen94 sorry 
I tried removing `node_modules/react-native-video-processing /node_modules` folder. But no luck.
there is no `react` in package.json of `react-native-video-processing` 

same error

**Comment by shahen94** [comment]
@matart15 Did you stop and rerun the package ?

**Comment by matart15** [comment]
Yes i eve tried `rm -rf $TMPDIR/react-* && watchman watch-del-all && rm -rf ios/build/ModuleCache/* && rm -rf node_modules/ && yarn cache clean && yarn`

**Comment by matart15** [comment]
@shahen94
ok I figured it out. in `podfile` i had this.
```
  pod 'React', path: '../node_modules/react-native', :subspecs => [
      'Core',
      'RCTActionSheet',
      'RCTGeolocation',
      'RCTImage',
      'RCTLinkingIOS',
      'RCTNetwork',
      'RCTSettings',
      'RCTText',
      'RCTVibration',
      'RCTWebSocket'
  ]
```
`react-native-maps` instruction required it.

But it works if i comment out these lines.
I wonder how other dependencies like `react-native-video` and `react-native-camera` were working with 2 `react` installed.

**Comment by matart15** [comment]
Closing the issue

**Comment by zachrnolan** [comment]
I'm having the same exact issue, but I'm not using cocoapods, so @matart15's fix doesn't apply. I also attempted to remove react from the react-native-video-processing package.json and I'm still getting the same error. 

My app is building without errors and it's not until I open the camera library that this error comes up. If I remove react-native-video-processing, the error doesn't show up.

Any ideas @shahen94?

**Comment by zachrnolan** [comment]
@shahen94 Nevermind, the problem was React in the dependencies in package.json. I moved it to peerDependencies in my fork and created a PR for you: #81
