### ISSUE TITLE
getting an error when testing with sample code

### ISSUE THREAD

**Issue by ranjitpandit** [shahen94/react-native-video-processing#62]
Hi, I tried creating a sample project to test out the module but I'm getting this error when the application loads.
I followed all the steps as given in the Readme and  I'm just using the example code
Here is a screen shot. 
I have tried a number of things but I'm always getting this error.  Any ideas?

![screen shot 2017-05-01 at 3 58 00 pm](https://cloud.githubusercontent.com/assets/2948979/25597974/fa529a20-2e86-11e7-948b-3b6d788a41d8.png)

**Comment by shahen94** [comment]
You didn't compile sources. Watch the demonstration video 
https://github.com/shahen94/react-native-video-processing#how-to-setup-library
