### ISSUE TITLE
What does this do? [REQUEST - Update Description by adding Features / Snapshots]

### ISSUE THREAD

**Issue by garrettmac** [shahen94/react-native-video-processing#64]
I noticed the video didn't show it in action and I didn't see a description describing this project, rather, it just shows how to set it up.

by looking at your code from my understanding it does the following:

* records videos
* allows you to trim the video before you save
* save to camera roll

is that correct?

Any snapshots would be great or a description of its features would be great.

**Comment by shahen94** [comment]
I think this screenshot will answer your question
![screen shot 2017-05-12 at 11 44 37 am](https://cloud.githubusercontent.com/assets/13334788/25988333/a44a94b8-3708-11e7-8227-403eaa98abe2.png)
