### ISSUE TITLE
Android only: no progress bar or indicator in trimmer

### ISSUE THREAD

**Issue by JBerendes** [shahen94/react-native-video-processing#65]
It seems like this is missing on Android. Could be something I'm failing to do configuration-wise or it was never implemented. Or maybe this should just be considered a feature request. Thoughts? My time to dig into it has been short as of late but should some open up I'll let you know if I start working on it.

**Comment by shahen94** [comment]
agreed, good catch - we can have optional loader.
Trimmer for android implemented in JS side, so that's should be easy to maintain.

**Comment by AlmogRnD** [comment]
+1

**Comment by shahen94** [comment]
Closing this due to long inactivity, Probably this issue has been fixed in the master branch
