### ISSUE TITLE
ffmpeg not resolving correctly

### ISSUE THREAD

**Issue by JBerendes** [shahen94/react-native-video-processing#67]
Error:Failed to resolve: com.github.kesha-antonov:ffmpeg-android-java:e69ea470d69d271fafbd03d0a4b0ea67d6731ccc

@kesha-antonov, what actions need to be taken to get this dependency working?

This is a breaking bug for me.

**Comment by shahen94** [comment]
@JBerendes Do you mean the android version is broken ?

**Comment by JBerendes** [comment]
Yes the android version is broken for me. Please confirm if you can.

**Comment by shahen94** [comment]
ok - i'll test it tomorrow, and will write about result here

**Comment by kesha-antonov** [comment]
@JBerendes 
Did you add ? 
<img width="781" alt="screen shot 2017-05-31 at 01 11 11" src="https://cloud.githubusercontent.com/assets/11584712/26607217/14dabc82-459e-11e7-9496-1dc1a802d516.png">

**Comment by shahen94** [comment]
Closing this due to long inactivity
