### ISSUE TITLE
Library not loaded: @rpath/GPUImage.framework/GPUImage

### ISSUE THREAD

**Issue by petrgazarov** [shahen94/react-native-video-processing#68]
```
dyld: Library not loaded: @rpath/GPUImage.framework/GPUImage
  Referenced from: /var/containers/Bundle/Application/6C9C98B2-35FE-4847-B7C8-D6D1B54B4E83/<MyAppName>.app/<MyAppName>
  Reason: image not found
```

Hey there,

Unable to load on real iOS device (works in Simulator). Both Clean and Build succeeds in XCode, but getting the above error when the app tries to open on my iPhone.
Did all setup steps for iOS, tried restarting Xcode and computer, no help.
`GPUImage.xcodeproj` is definitely on the "top" level, along with `RNVideoProcessing`.

Here is the contents of my bridging header file:
```
//
//  <MyAppName>-Bridging-Header.h
//  <MyAppName>
//
//  Created by Petr Gazarov on 6/4/17.
//  Copyright © 2017 Facebook. All rights reserved.
//

#ifndef <MyAppName>_Bridging_Header_h
#define <MyAppName>_Bridging_Header_h

#import "RNVideoProcessing.h"

#endif /* <MyAppName>_Bridging_Header_h */
```

`<MyAppName>` replaced the actual app name.
I also attempted [this fix](https://stackoverflow.com/a/25772532/4493564), but no avail.
Tried version `1.8.0` of this library, as well as `latest` and directly from `master`.

Is it intended that the app is looking for `@rpath/GPUImage.framework/GPUImage` whereas the actual file name is `GPUImage.xcodeproj`?

-----
**Environment**
MacOS Sierra 10.12.5
XCode 8.3.2
iOS 10.2.1
react-native `0.44.2`

**Comment by shahen94** [comment]
That's weird to me.
Are you sure that you installed library as demonstrated in video ?
https://www.youtube.com/watch?v=HRjgeT6NQJM&feature=youtu.be

**Comment by rad182** [comment]
I'm also getting this error. I follow the video. no luck.

**Environment**
MacOS Sierra 10.12.5
XCode 8.3.2
iOS 10.2.1
react-native `0.43.4`
react-native-video-processing `1.10.0`

**Comment by gcheong** [comment]
I was getting this error until I saw the video mentioned above (only followed directions on github until that point) and realized I did not do the step of adding the GPUImage.framework under Embedded Binaries shown at 2:37.

**Comment by shahen94** [comment]
Closing this due to long inactivity, Probably this issue has been fixed in the master branch

**Comment by tlays11** [comment]
To anyone who cannot find the embedded binaries section on "Build Phases" like I could not, it is not located on the "General" tab

**Comment by nikage** [comment]
I'm new to xcode and react native. But why the is no Embedded binaries on General tab?
XCode Version 12.4 (12D4e)
![image](https://user-images.githubusercontent.com/42967644/107558853-f8273780-6be3-11eb-87ba-c6ca3f7c8775.png)

**Comment by tuanphamhnl** [comment]
@nikage did you find how to add to Embedded binaries?

**Comment by nikage** [comment]
> @nikage did you find how to add to Embedded binaries?

To be honest I don't remember how I did it. But it seems to me it works on newer versions of xcode.

<img width="804" alt="image" src="https://user-images.githubusercontent.com/42967644/167381572-047674c5-7928-4bb2-8155-c110b3940da7.png">
