### ISSUE TITLE
Extract thumbnail from specific moment of video?

### ISSUE THREAD

**Issue by GeoffreyPlitt** [shahen94/react-native-video-processing#74]
Is there a way to extract an image from a specific timecode or frame number?

**Comment by shahen94** [comment]
Hi @GeoffreyPlitt .
Sure - Have a look https://github.com/shahen94/react-native-video-processing#usage

```
ProcessingManager.getPreviewForSecond(source, forSecond, maximumSize)
      .then((data) => console.log(data))
```

**Comment by xpertystanalyst** [comment]
@shahen94  getPreviewForSecond is not working for android. how to get it for android also?

**Comment by shahen94** [comment]
This should work on android as well @xpertystanalyst

**Comment by Subiyel** [comment]
I tried this library to get thumbnail for a video. Sadly getPreviewForSecond() does not work on Android.
It Throws setDataSource failed status.
