### ISSUE TITLE
Getting android build error

### ISSUE THREAD

**Issue by gevorg94** [shahen94/react-native-video-processing#75]
Sometimes I'm getting this error
```
:react-native-video-processing:processDebugAndroidTestManifest FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-video-processing:processDebugAndroidTestManifest'.
> Manifest merger failed : uses-sdk:minSdkVersion 16 cannot be smaller than version 17 declared in library [com.github.kesha-antonov:ffmpeg-android-java:e69ea470d69d271fafbd03d0a4b0ea67d6731ccc] /Users/andrew/src/jh-mobile/node_modules/react-native-video-processing/android/build/intermediates/exploded-aar/com.github.kesha-antonov/ffmpeg-android-java/e69ea470d69d271fafbd03d0a4b0ea67d6731ccc/AndroidManifest.xml
     Suggestion: use tools:overrideLibrary="com.github.hiteshsondhi88.libffmpeg" to force usage
```

Where do we need to add `tools:overrideLibrary="com.github.hiteshsondhi88.libffmpeg"` to avoid that? @kesha-antonov 
My `minSdkVersion` is 17 in both AndroidManifest.xml and app/build.gradle

**Comment by gevorg94** [comment]
I tried to add `tools:overrideLibrary="com.github.hiteshsondhi88.libffmpeg"` in my project's manifest but it doesn't help. Seems it should be added to your library.

**Comment by kesha-antonov** [comment]
Hey!
Do you have this?

https://github.com/shahen94/react-native-video-processing/issues/67#issuecomment-305023617

**Comment by gevorg94** [comment]
yes @kesha-antonov. Described error appears after android studio's indexing complete but it disappears after pressing build app and the app successfully build.

**Comment by gevorg94** [comment]
I just want to know if we can prevent it

**Comment by kesha-antonov** [comment]
I don't know.
I build android through CLI (not android studio)

**Comment by JBerendes** [comment]
@gevorg94 Plenty of libraries give me grief like that. I find a postinstall hook in the package.json is the best option since we are all working on the bleeding edge. This covers more than react-native-video-processing but you should get the idea. 

a section of my scripts in package.json::
```"patch-rnvp1": "sed -i -e 's/minSdkVersion 16/minSdkVersion 17/g' 'node_modules/react-native-video-processing/android/build.gradle'",
    "patch-rnvp2": "sed -i -e 's/23.0.1/25.0.0/g' 'node_modules/react-native-video-processing/android/build.gradle'",
    "patch-rnmm": "sed -i -e 's/23.0.1/25.0.0/g' 'node_modules/react-native-media-meta/android/build.gradle'",
    "postinstall": "npm run patch-rnvp1; npm run patch-rnvp2; npm run patch-rnmm;",```

**Comment by JBerendes** [comment]
@gevorg94 Did you get your build working per my solution? If so I think we could add it to the readme and close the issue.

**Comment by gevorg94** [comment]
No I haven't tried to build with your solution yet. I will try it soon

**Comment by JBerendes** [comment]
@gevorg94 also note the solution I provide only works if you already have your project open in Android Studio... the build.gradle files for each node module won't exist until Android Studio does a sync. So the other solution would be to not run a postinstall hook and instead just note that you have to execute that as a standard script afterward.

In this order: 
1. npm install
2. Open the project in Android Studio
3. npm run gradlePatches (or whatever you want to call it)

**Comment by JBerendes** [comment]
close please

**Comment by zachrnolan** [comment]
For anyone searching like I was, I fixed this by adding the following to my `AndroidManifest.xml`:

```
<uses-sdk tools:overrideLibrary="com.github.hiteshsondhi88.libffmpeg"/>
```

**Comment by shahen94** [comment]
How i could forget that, ya i guess you're right.
I got an error when `gradle` sync the project, but when i build project - it built without any error. If you guys are getting an error when gradle starts sync the project - add this line to the manifest file - the gradle sync error should be fixed.

@zachrnolan if we'll add this line to the manifest of our project, can it fix gradle sync error ?

**Comment by zachrnolan** [comment]
@shahen94 I got the error when trying to build my project on Android `react-native run-android` after doing the initial install in the readme. It wouldn't build until I added the uses-sdk line above.
