### ISSUE TITLE
VideoPlayer throws `EXC_BAD_INSTRUCTION`

### ISSUE THREAD

**Issue by rpastorelle** [shahen94/react-native-video-processing#80]
![screen shot 2017-06-30 at 3 42 20 pm](https://user-images.githubusercontent.com/746320/27751534-ca6ceba0-5daa-11e7-84af-d892c07416a5.png)

I'm having a difficult time using the `VideoPlayer` component (on iOS). Here is my component:

```
<VideoPlayer
    ref={ref => this.videoPlayerRef = ref}
    source={this.props.uri}
    style={{ backgroundColor: 'black' }}
    resizeMode={VideoPlayer.Constants.resizeMode.CONTAIN}
/>
```

Do you know why I get this error? Could you document the usage a little better?

**Comment by shahen94** [comment]
oh, that's so weird. Seems like your player didn't initialized yet, but it wants to set `currentTime` prop, and since player is null, `player.currentTIme()` throws an error

**Comment by NLebedev** [comment]
I am getting the same error. @rpastorelle did you manage to solve this?
@shahen94 any idea what it might be? At least where to look?
Thanks

**Comment by shahen94** [comment]
@NLebedev please try to set `currentTime=0` . I'm wondering do we have race condition or not

**Comment by shahen94** [comment]
I'm going to close this due to long inactivity. Feel free to reopen other issue if this issue still exists in the code.
Thanks
