### ISSUE TITLE
[Android] Attempt to invoke virtual method 'int android.graphics.Bitmap.getWidth()' on a null object reference

### ISSUE THREAD

**Issue by zachrnolan** [shahen94/react-native-video-processing#82]
RN 0.45.1

```
onCaptureMedia(mediaData) {
    console.log('mediaData: ', mediaData)
    const maximumSize = { width: 1080, height: 1080 };
    ProcessingManager.getPreviewForSecond(mediaData.path, 4, maximumSize, 'JPEG')
      .then(thumbnail => {
        console.log('previewForSecond: ', thumbnail)
        this.props.dispatch(PostReactionState.videoRecorded(mediaData.path, thumbnail))
      })
  },
```

I get a console.log for `mediaData` with a valid path to the video file. I never see the console.log for `previewForSecond`.

This works fine on iOS.

![image](https://user-images.githubusercontent.com/66614/27837161-8d6ef474-6097-11e7-975d-9a5a69bc0dd8.png)

**Comment by shahen94** [comment]
I guess your video is very short < 4sec is it right ?

**Comment by zachrnolan** [comment]
@shahen94 you're right, I think it was right around 4 seconds. I tried a longer video and it seems to work fine. I do notice that android doesn't give me a width/height though. I'm using a Samsung S7.

**Comment by shahen94** [comment]
do you mean that the `ProcessingManager. getVideoInfo()` doesn't give width/height ?

**Comment by zachrnolan** [comment]
ProcessingManager.getPreviewForSecond will return an object with uri, width, height on iOS. However, on Android, it returns uri, but width/height are undefined.

**Comment by shahen94** [comment]
Yes - that's right.
We're not sending it from native
https://github.com/shahen94/react-native-video-processing/blob/master/android/src/main/java/com/shahenlibrary/Trimmer/Trimmer.java#L360

**Comment by zachrnolan** [comment]
Got it, is this something that will be added in the future? I can close this task as it's unrelated.

**Comment by shahen94** [comment]
We can if needed, it's a very simple feature, but i'll prefer to use `getVideoInfo` since it will give you what you need.

**Comment by zachrnolan** [comment]
Ok, I'll check that method out for now. Thanks for your help!
