### ISSUE TITLE
Possible to concatenate videos?

### ISSUE THREAD

**Issue by CaptAhak** [shahen94/react-native-video-processing#83]
Hi there,

is it or will it be possible to take multiple videos as input trim them and then concatenate them into one video file which can then be saved to camroll or something?

Just a question, so feel free to label it as such or close it right away if it disturbs you, but maybe it can also be seen as a enhancement idea. 

Thanks in any case

**Comment by shahen94** [comment]
Hi @CaptAhak .

No - We don't have similar feature. But it's a very simple feature and you can achieve that with 30 line of code for both platforms.

Unfortunately i don't have so much free time in these days to work on it, but i'll accept PRs if someone will be able to do that.

**Comment by CaptAhak** [comment]
Thanks for your answer.  I found and used to quickstart:
[https://github.com/MostWantIT/react-native-video-editor](url)
Which concatenates multiple videos. The Rep wasn't updated for a while but works nicely so far (on Android, RN Version 0.45). Next step for me is to preprocess the videos with your library and then merge them with the module above. 

A PR here would probably be the more elegant way, but I am both new to RN as well as Video Processing, so I wouldn't count on that. But maybe you can point me in the right direction.
From what I understand Android-side uses FFMpeg and/or MP4Parser, Whereas iOS uses Core-Stuff and GPUImage. So I would need to talk to those libs on the respective sides?

**Comment by shahen94** [comment]
Correct - Open Trimmer.java file, and you'll see the main processing methods there (android).
For iOS the main processing methods are located in RNTrimmerManager.swift file

**Comment by saputroandhi** [comment]
> Thanks for your answer. I found and used to quickstart: [https://github.com/MostWantIT/react-native-video-editor](url) Which concatenates multiple videos. The Rep wasn't updated for a while but works nicely so far (on Android, RN Version 0.45). Next step for me is to preprocess the videos with your library and then merge them with the module above.
> 
> A PR here would probably be the more elegant way, but I am both new to RN as well as Video Processing, so I wouldn't count on that. But maybe you can point me in the right direction. From what I understand Android-side uses FFMpeg and/or MP4Parser, Whereas iOS uses Core-Stuff and GPUImage. So I would need to talk to those libs on the respective sides?

I has been try, but cant bundle for release the classname conflict with react-native-video-editor any update ?

**Comment by jymnkn** [comment]
> Thanks for your answer. I found and used to quickstart: [https://github.com/MostWantIT/react-native-video-editor](url) Which concatenates multiple videos. The Rep wasn't updated for a while but works nicely so far (on Android, RN Version 0.45). Next step for me is to preprocess the videos with your library and then merge them with the module above.
> 
> A PR here would probably be the more elegant way, but I am both new to RN as well as Video Processing, so I wouldn't count on that. But maybe you can point me in the right direction. From what I understand Android-side uses FFMpeg and/or MP4Parser, Whereas iOS uses Core-Stuff and GPUImage. So I would need to talk to those libs on the respective sides?

Hello, have you achieved the concatenation of the videos ?
