### ISSUE TITLE
ProcessingManager Android Error

### ISSUE THREAD

**Issue by CaptAhak** [shahen94/react-native-video-processing#84]
Hi,

I am trying to use the ProcessingManager exactly as described in the example, but I am getting the following error:
> undefined is not an object (evaluating '_reactNativeVideoProcessing2.default.getVideoInfo')

Not sure what to make of that. I am on Android, RN Version 0.45. react-native run-android builds the app without problems, but as soon as I try to call any function of the ProcessingManager, I get the the above error.

**Comment by shahen94** [comment]
```
import { ProcessingManager } from 'react-native-video-processing'
```
Please import processing manager as mentioned above

**Comment by shahen94** [comment]
Please take a look example

**Comment by CaptAhak** [comment]
You are right. Sorry, what I did was:
import ProcessingManager from 'react-native-video-processing'``

Been glaring over the example again and again but didn't notice I was missing the parentheses.

Thank you!
