### ISSUE TITLE
Android compress and crop block the UI thread until the operation completes

### ISSUE THREAD

**Issue by mannol** [shahen94/react-native-video-processing#90]
The UI thread is blocked because the ffmpeg command is not executed asynchronously. AsyncTask should be used to avoid this issue. @kesha-antonov

**Comment by kesha-antonov** [comment]
@mannol Yes, it is. Please do PR
I'm not maintainer and I help this project as I have free time

**Comment by kesha-antonov** [comment]
I'll send PR today/tomorrow
