### ISSUE TITLE
Undefined is not an object (evaluating '_reactNatuve.UIManager.RNVideoProcessing.Constants')

### ISSUE THREAD

**Issue by iMagdy** [shahen94/react-native-video-processing#93]
```
react-native-cli: 2.0.1
react-native: 0.47.2
```

I did `npm i --save react-native-video-processing`, then followed the Manual Installation tutorial (no react-native link).

However, I'm getting this error:
![image](https://user-images.githubusercontent.com/611426/30070790-df0ac278-9264-11e7-969f-a3c93575305e.png)

Please help @shahen94 as I've tried re-installing this multiple times, but it seems `UIManager` isn't seeing `RNVideoProcessing` for some weird reason.

**Comment by shahen94** [comment]
Hi  @iMagdy !
The library written in Swift - that's why it's not easy to integrate in react-native project
Please revert all your changes and watch this Demo video.
https://www.youtube.com/watch?v=HRjgeT6NQJM&feature=youtu.be

This should help.

**Comment by iMagdy** [comment]
@shahen94 Thanks for your prompt response, I've already followed this video (mentioned in my original comment above).

I'll give it another go.

However, I'd appreciate if you give me any idea on the following questions:

- How to make sure that I've really completely reverted everything?
- Is dropping the entire dir of `ios/RNVideoProcessing` into the project root is as same as manually creating groups one by one?

Thanks so much

**Comment by shahen94** [comment]
@iMagdy 
- just what you did for manual linking - revert all that changes(remove added files, undo included libraries)

- NO - it's not the same - you should manually create groups one by one.

**Comment by MatheusParanhos** [comment]
Hi @shahen94, I'm having the same issue, I'm following you video on youtube and noticed that the same compile sources as you do. Should I add them manually? I also notice that I don't have the same imports on ProjectName-Bridging-Header.h. Can be that the causes of the errors?

**Comment by shahen94** [comment]
Definitely yes! 
You should manually create groups and add imports correctly

**Comment by iMagdy** [comment]
@shahen94 After reverting all changes, and creating groups manually, it finally works fine now!

Thanks a lot, I figured out the issue was dropping the entire directory instead of manually creating each group.

**Comment by WillyRamirez** [comment]
@shahen94  could you please comment on how many bridging files you have?
xcode created one for me in the RNVideoProcessing folder after creating the first group, and i manually created the one in my project name as seen in #144. However im still getting this error. I followed all the other steps from the video.

**Comment by 18059842153** [comment]
@shahen94 Hello, this library can still support the current react-native?

**Comment by 18059842153** [comment]
@shahen94 In my xcode project, my project name file does not contain AppDelegate. Swift and header.h，I did it through react-native init my project

**Comment by UpendraGurujala** [comment]
@shahen94  I am trying to use your library in the react native expo app (version 0.71), the demo video is little confusing, I am using windows machine and testing mostly in android device, do you have any steps to fix the problem for me.

the error I am getting is **TypeError: Cannot read property 'Constants' of undefined, js engine: hermes**
