### ISSUE TITLE
Operation is not supported for this media

### ISSUE THREAD

**Issue by iMagdy** [shahen94/react-native-video-processing#94]
@shahen94 I'm getting this error once I run the trim operation using either mp4 or mov videos:

```
const source = require('test.mov');
    const options = {
      startTime: milliseconds,
      endTime: milliseconds,
      saveToCameraRoll: false,
      saveWithCurrentDate: false
    };
    ProcessingManager.trim(source, options).then(data => console.log(data)).catch(err => { console.error(err); });
```

`ProcessingManager` was able to successfully read the video file, and deliver accurate duration/length for the video (`getVideoInfo`), however (`trim`) is failing with the below error.

Any idea what can be the reason? Should I specify quality in the options?

![image](https://user-images.githubusercontent.com/611426/30162953-44b7ccec-93d7-11e7-8069-1e2cf53e8097.png)

**Comment by shahen94** [comment]
@gevorg94 can you please  take a look at this issue ?

**Comment by iMagdy** [comment]
@gevorg94 @shahen94 Does `react-native-video-processing` only support MP4 videos? Or does it also work with MOV videos on iOS?

**Comment by gevorg94** [comment]
@iMagdy can you choose video from assets library? Currently trim doesn't work for `required` assets.

**Comment by shahen94** [comment]
@iMagdy it works with MOV files

**Comment by iMagdy** [comment]
@gevorg94 Confirmed, it works with document dir. 

Thank you.
