### ISSUE TITLE
App closes when Android tries to compress

### ISSUE THREAD

**Issue by ricardofavero** [shahen94/react-native-video-processing#95]
I'm trying to compress a video on Android, but the app closes and I get this error on Android Studio when I try to do it. I read [this](https://stackoverflow.com/questions/36693887/what-is-fatal-signal-6-in-android-logcat) and it may have to do with too much work going on the main thread.
Does anyone know more details about it?

`A/libc: Fatal signal 6 (SIGABRT), code -6 in tid 19112 (mqt_native_modu)`

Cloned from master today and using RN 0.47

```javascript
const compressOptions = {
      width: 720,
      height: 1280,
      bitrateMultiplier: 3,
      saveToCameraRoll: true,
      saveWithCurrentDate: true,
      minimumBitrate: 100000,
    };

ProcessingManager.compress(response.uri, compressOptions).then((data) => {
    console.log(data);
});
```

**Comment by shahen94** [comment]
hi @ricardofavero !
Can you please try to install the library from github instead of npm ?
It should be fixed in master

**Comment by ricardofavero** [comment]
hi @shahen94 
I have the github version already

my package.json
`"react-native-video-processing": "git+https://github.com/shahen94/react-native-video-processing"`

**Comment by ricardofavero** [comment]
I fixed it. My response.uri was in an incorrect format. It's working fine with the correct uri now.

**Comment by vvavepacket** [comment]
@ricardofavero  is this a correct format for URI? content://media/external/video/media/22833 my app is also crashing same as yours.

**Comment by VrajSolanki** [comment]
@shahen94 what is the correct format for video path in android?? My path is something like @vvavepacket 
eg: content://media/external/video/media/62681 and the app seems to crash

**Comment by thatgriffith** [comment]
See my solutions in another issue here: https://github.com/shahen94/react-native-video-processing/issues/142#issuecomment-929957203
It should solve the problem with incorrect uri where file starts with `content://`
