### ISSUE TITLE
Video doesn't replay even when "replay" attribute is set to true

### ISSUE THREAD

**Issue by slickdev** [shahen94/react-native-video-processing#97]
react-native: 0.48.3
react-native-video-processing: 1.12.5
platform: iOS

When specifying replay={true} in my VideoPlayer component, the video still only plays once.

Update: occassionally the video will replay once and then stop. Haven't been able to determine which use-cases cause it to loop.

**Comment by shahen94** [comment]
Closing this due to long inactivity, Probably this issue has been fixed in the master branch
