### ISSUE TITLE
Changing resizeMode doesn't seem to have an affect on VideoPlayer

### ISSUE THREAD

**Issue by slickdev** [shahen94/react-native-video-processing#98]
react-native: 0.48.3
react-native-video-processing: 1.12.5
platform: iOS

I'm not sure what's happening behind the scenes here but when I alter the resizeMode attribute on <VideoPlayer /> it doesn't seem to affect the video.

The issue I'm facing is this: my app loads videos from the device, sometimes the video is landscape sometimes it's portrait. Since I've determined a fixed height for the video, the portrait videos show up fine (there's some black space on the sides but that's expected). However when a landscape video is loaded, the fixed height in the video player causes there to be black space at the top of the video.

Do you have any suggestions on how to solve this issue? Is it related to the resizeMode attribute not working properly?

Edit: does react-native-video-processing use the react-native-video library? I came across this open issue on that: https://github.com/react-native-community/react-native-video/issues/330

**Comment by shahen94** [comment]
resizeMode has been removed from iOS - due to some issues. But it should work on Android.
No - we're not using react-native-video. We created custom Video component to have better accesses with native APIs

**Comment by shahen94** [comment]
https://github.com/shahen94/react-native-video-processing/commit/dd3d14d010dde3e6f8f8fea18d81845cf40ccfa6
